apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://releases.rancher.com/server-charts/latest
    chart: rancher
    targetRevision: ${RANCHER_CHART_VERSION}

    helm:
      valuesObject:
        hostname: ${RANCHER_HOST}
        replicas: 2
        antiAffinity: required
        topologyKey: kubernetes.io/hostname
        ingress:
          enabled: true
          ingressClassName: traefik

          tls:
            source: secret
            secretName: rancher-tls

        # TLS terminates at Traefik / the Ingress
        tls: ingress
        service:
          type: ClusterIP

  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/antblu/antalos.git
    targetRevision: main
    path: apps/rancher
    plugin:
      name: yaml-envsubst
  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
