apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://releases.rancher.com/server-charts/latest
    chart: rancher
    targetRevision: 2.15.0

    helm:
      valuesObject:
        hostname: rancher.antblu.net
        replicas: 2
        antiAffinity: required
        topologyKey: kubernetes.io/hostname
        ingress:
          enabled: true
          ingressClassName: traefik

          tls:
            source: secret
            secretName: rancher-tls

        # TLS terminates at Traefik / the Ingress
        tls: ingress
        service:
          type: ClusterIP

  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true