apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default

  sources:
    # Source 1: the MetalLB operator (chart)
    - repoURL: https://metallb.github.io/metallb
      chart: metallb
      targetRevision: ${METALLB_CHART_VERSION}
      helm:
        releaseName: metallb
        valuesObject:
          controller:
            affinity:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchLabels:
                        app.kubernetes.io/component: controller
                    topologyKey: kubernetes.io/hostname
    # Source 2: the config (IPAddressPool + L2Advertisement)
    - repoURL: https://github.com/antblu/antalos.git
      targetRevision: main
      path: apps/metallb
      plugin:
        name: yaml-envsubst
        env:
          - name: METALLB_IP_RANGE
            value: ${METALLB_IP_RANGE}

  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true