apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default

  sources:
    # Source 1: the MetalLB operator (chart)
    - repoURL: https://metallb.github.io/metallb
      chart: metallb
      targetRevision: 0.16.1
      helm:
        releaseName: metallb
        values: |
        controller:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app.kubernetes.io/component: controller
                  topologyKey: kubernetes.io/hostname
    # Source 2: the config (IPAddressPool + L2Advertisement)
    - repoURL: https://github.com/antblu/antalos.git
      targetRevision: main
      path: apps/metallb
      directory:
        include: '*.yaml'
        exclude: 'app.yaml'

  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true