apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-db-app
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  encryptedData:
    username: AgCZRG6kXvfXAC6CLbSru1RTHkwCKTSzuzUHuMEJcgQNHz17CX6ZmbQakGLbt39/GDKtyGeRTGZ2D2/OTHIuDXCL5SeJpF7NWArgvnSR+3EaAKv5dL0mLWb48hxzOIdJjQVwwydzW2zslDzUUfuJrlMKVZ25q7gTQxkS1smw/FryFRJeP1eMumxbKsFc17ugUsocoAriLW+U29XjYbq4a87wOT1xkZYNja+hsw1MvVhf1exuON5Aqcqt71SpsybH2qB5TmJ7GElaL17ll/IqBmNadEKlBgeBtXqjp7Ms7lSzqzC/m99/xxjebClkMIPT735ZjEUcCINkyEBBnWtEk1k5UkPV6brQc4f82VlZvotYqKBY+4WlCSwj+67QFlHuRWKg0Ns6RUJZ/NEav5/VbSU1gb4Fc0/cZxu3kbnhhI+WYFd+33BAXMEjZ2epph5OY4/CnR5ejA5keW4xCWW+j4ZRtF77Ir9cDOTc0CfN4ApJV3cyB0hsplJKegKhCgEQu5TA2cHe1w2MTpRyWB4InWdorCW1TUSQIBLsSDS4NqV4hjL+vxB6g+G9edfM423Y1E+aMBe35fisx9YveAcbkBP9Uj+09hOEOb4WoVTYShSL0C5L0YLYW2jqeTDvpczl0e0Nexq6zb5VQywbQQ4R04Zn63HotbI3oeqTLBD0N/Hob48u5v5NbrJOeZtxa2VZqIY1jBP1neKC
    password: AgCIPrNOzDJZK7DzYmL4OwJI4Gej0JicXW8vf6eod1Y1MevjRgNSoVi+cmWDLMbzei6JkKmaE5ybCJyhktrPAAGev31WxA+rfVqAqezULgxiTTP3qcjXr65Jb7dzVDQbXmlvy1GfWBJNjKm4O8UhhimUBQgEjiJj7P7a7sYsrXxP+T/ZnZFQHGQexN+mWo7lJUjz1BypcQ43ijzvSnnoFRY5HQKJpPADM7CaEJMknmakYASWERCLswYUj6HJ1AhvDTxV5NgQoFgJwy0y88RUjvnzK2XrimL4TwW/pQXYoCtdCyH8RFPe5CLaUUhQpLAnujaco860cPW0NFiShTqwMTS09IOJRLnhZo/lBZXYLOzPqGLaoQj8uq1Qlj3fcqx3OHz8cTBlGoy2cS1LIP4F3vxtRLonk7OnzSWLG2DDQ/LxxUPRjmiDPwSe2h8swV8ZNcehHmXvdWziiSxeNx8Y4DuAClQ80Wnl5GLv+2Ul6cs9S4rHCuMjKlVo5vLuGllbTfVoItsR4SDBgUcF/7IZOuWqLL/H5KeA30l0OQLCwJGNel2U2+zgaDa22t+JCZWS4qVseq4E6c9h3tQsZjk5puQQh1wOhOhZNOm9Zu6MM9JbProSzrtf31MwkhgLRR8eOO27CK5OaLSy66ReAxsNTA9PkjUXfkSifBTjySMaYdH1MuJ87UZvjagt/Jb+Ez4dHNXZeQO9tRGiG7ywN5HW87cZAMTm3NL0GGwJ8I9ZFqKnmgWxbrFmSJNgNGNJ+bldGJ/STJrurSYcLMAoGFr+p7kh
  template:
    metadata:
      name: grafana-db-app
      namespace: monitoring
      annotations:
        argocd.argoproj.io/sync-wave: "-3"
    type: kubernetes.io/basic-auth
