---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-admin
  namespace: vaultwarden
spec:
  encryptedData:
    token: AgAv9kmwuQyI5Gth0R5sVDlfje67PPgzMaCYzF/Hc9urNEyyAYcak2kRF+NZLR3Dabw/kM+0axik0JpKPtdScITCr4fO82PVjrerzVCEkx42HrS7QFwRCWmcLOQr/6CcP4ZoQuYNDqIjFu1VUGB2rnIpmSRvCp/N3jIqhuhUi6/peU2gqMLJLsCp5hppUjhQkCrCz3kyBAjY11vI8jQvhcoG1aGIghoLAodZ9QumbrRqzQLiUFwv0R+BIcmx8ibxVGD994bESJwMQJQx/w3LLtf1j2buNefnrYjfzK1ylwjRI9vBn7cplblaDmvGYh+vr+E82nJ5fbw+cvGMBDF0J8Upk76b+6C7r4Q8Ejy5Vckmx2bd9DxpsphvW0ovUUCHx/ct0Fob9fjcYxPQ7tRxVtirCwp+ktkb31NRmk3cciE+1L7vL44sviQrd/47Omty5kNq/XMwWDCqpPzjSrgS3xgIdx9aKwVfrcvSQ4zPnpHcFAb8oh1KUHOT5pp9wNw7FYRp9I6TBylk6rYL3PB1/9t6zpaGKPkdnRF7U2Ij7ARjqu1st9S49/MhLzKPh7j+e+ZWMvLM2byFvRLCkKBntOwAVl7tZsYhePTyYJZkndjtdAySXa7Ldr5Uq1y/6bAKuOSjUGQKo7/T1vkXar4oo24eu5mtjE4eJQtcrCz8RGXS9ROUoCTM4BMiPG+vPUBcOirBUFvrcDsazqVQiS9E7kIeUm2ZUGFQumUyAZ/sQRXVqs8tJYs1BzKhUS2PoL3BBMkwiVwd72UGaPzRLBpCA8SA
  template:
    metadata:
      name: vaultwarden-admin
      namespace: vaultwarden
    type: Opaque
