---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-db-app
  namespace: vaultwarden
spec:
  encryptedData:
    password: AgB3aLDtmZP58q4EKkfedOz4AkwLO8at+mqxRtCQvsbf1kn8UJji6t6HZWFi+jK6moPJuXddxF1WFhE9zlJjh4BmDIDr75QuWBbYtYjDsxPyW2QEjRo3XVQdFh3AUraSDOxdP27k0Hjfjfc7AiN6Y2kfvMrncCJzSIcLlMwbO7UF1xI5MQ9GJ+r1spXhgn27/afG+tYO/Z4FBfEO8dl4ksgQVQuojhIEkF07BMZoCYYgS5i5AzY72lLS6wQj51sZu1iU3cntsVZOZu5RhPdK8JHb47xXbhNyJm4JLCx8iUKJ2kdKvdGGap/6Nsb/qGOPxoFanU7qxX5QEuh35H4pET5D/8OFz1ROXJcgWda78SW6/PxvM93HVp26VIef95HFTNK//k3CdaEkGDUddbN4tfoKqEaEdquTesxOfWb4ObaZAA0OKQp4y/7NlxZGodydxnUzr0GqO2CdaSgrPYX0G12dgDNZkY3ZO1YuUcQb472kI5zI69Chn0AJh0AB6qnsPwPAbMmsACOZtcgQSCPP8nPMhdTuJkm70F3Owpy+DsQaw2l9MrYaYPg/U4ujwglLZ9Jc/MPaqe7pS2rD6q0Mwx6lB6QLILQemPRya1HzA2w9ZP3NMV9gOW8FeAxPgDpyjbrT0u1wFV+TMnGh8jW44V56w7kQu2hMVO/621wMCECU3xdwTotxM2JIzDBO9m8LoqsM62IP9mNv5QWPjG8EFYJXpvHroxVdf7y9dTzqAHU0+2nNF9ziQrR3LJxguRo4JHco+NRyfZMgL5SCYIzNBOBU
    username: AgAe4etN9Y6dk18iuE6LCTBX5E4FiXK2laZo4elnVG2Dfgl7NrXi/ICBsJkdseMorimgvto1FvRILUN/SyzX/6WYvzl4sP/p1U0z5lKKLFa8RR9Ap9foYAlbvyG6H2ioXufhzJDGR+KPU+8mZ7cqeIzPngiKO48EW3DYkzb2O1F32hwY8oE/rrdzHpdMoUey55bC1YrrSJiC1yLR/BHCFzxsu3hBSyM2qkKv6SO8aJwQTRvRYA5DDt+H9se6qlnf8HigM3B8tTrQqyiuCuSE20dAbIQ4/wL9XT1J3P/dsmoTHngW+KqaNMMlq248Za2VtW8JElAm0OdUOMh9oOLAhMC/h2EMFIuWG4uIJEQp5+/B6B7w/a6T+XVxFQ8+bLwvtHEwPf+9Fla3vFLf/8f24GN1lg//DC8Sk9+3HHE6XrQgJ76HzEh1/pk/md0G2FdhRRfszu9soEjfgYo+WGoHOJtcLMpHu58StjeoUxWPueD/tBJN8He2jMCWUpGQ1T6KwjvSz6z+xLoqt4nf0UtffZDmN/9LxuIXQlGvgxbn8qDbda/leFgPMcA3gYkLkgtAHJNhcevoN/DRXoGBFsHjKOP4gKSQO5tApQIynWT+0tRnCc92VO2ZNLCiSbeiHf82Qx67tvAeTDA/IJW5KYPFh8ns1QbLjQCF8nKQ0d0rYv9PD4+5S+0Gu3LOsHcWUyNJITv1z8TeDCIlJrvFGw==
  template:
    metadata:
      name: vaultwarden-db-app
      namespace: vaultwarden
    type: kubernetes.io/basic-auth
