apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-data
spec:
  capacity:
    storage: ${VAULTWARDEN_DATA_STORAGE_SIZE}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    name: vaultwarden-data
    namespace: vaultwarden
  mountOptions:
    - nfsvers=3
    - hard
    - nolock
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: vaultwarden-data
    volumeAttributes:
      server: ${NFS_SERVER}
      share: ${VAULTWARDEN_NFS_SHARE}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data
  namespace: vaultwarden
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: vaultwarden-data
  resources:
    requests:
      storage: ${VAULTWARDEN_DATA_STORAGE_SIZE}
