apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: activepieces-tls
  namespace: activepieces
spec:
  secretName: activepieces-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - ${ACTIVEPIECES_HOST}
