apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: headplane
  namespace: headscale
spec:
  encryptedData:
    cookie-secret: AgBhjTQk5GDcqXEcELtlpcE934TFTf+BdKH4uwbu77e7waddEyR11eH8lPyGdJfursAhfHcX2hFUlLQK0Vj7L/gEjcj4CMvZgVDVnsw8Yf20qHTbsJwtcJT/JC7RG/mrEP+QvLifsSJUvkvY8HobhFwvvWoHy2CCXDyhnsbLdziuSkWlJwle24sI1H1MuRT1/h7JNY86Fm2N4e/HiholjD2OD2djdF4BV2uHcE1cQ9gf36gNTuXjIUxeI439zUY+jCfL8VubtUFTmaMz4MItaMeCWjYRoFbd83DDZ73vlhLvKSk+Rp9gfmkheXsL+3n2+ovfcuEtj2PMzTWsPjJ6EN27YYMhHC6eOt4WLVdkSInvlKDzSz8mPv/DAMgDrCsXNJXPjUuk1kdz8EZYgOvIbmi6Y40JQooN1YBjmTN0qLP9ioSspTR3o3eiobpdPUKvaffXnSlQElz5t8vF5XvB2TFX0+gfzGp+G/IYB/uNf3xd5GtOUR3uLPxbQpVd9HtCrOR3jwFaeuEbkO/RXt38n/Z4sHZBgt+3u+BHsyNsE47RrAxmoDUb+H4sy9RjpdH0Fd9PrPJaVS18T8dKFiKZLZ4Vqu7CGzApwVYeC+fn+DeyNt1C2/hW5NjImLnNzO3qpM5reHks7gQv4g+jqdwY0XrNppm6MOyAFYeMA5ame44um0JjpkiVrnO/K/FVQVIsNjSP/H8UM9dTTAPhSMZnAYWFF/Hg9DzDhwkw1SwmIqTpag==
  template:
    metadata:
      name: headplane
      namespace: headscale
    type: Opaque
