apiVersion: v1
kind: PersistentVolume
metadata:
  name: headscale-backup
spec:
  capacity:
    storage: ${HEADSCALE_NFS_STORAGE_SIZE}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    name: headscale-backup
    namespace: headscale
  mountOptions:
    - nfsvers=3
    - hard
    - nolock
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: headscale-backup
    volumeAttributes:
      server: ${NFS_SERVER}
      share: ${HEADSCALE_NFS_SHARE}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: headscale-backup
  namespace: headscale
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: headscale-backup
  resources:
    requests:
      storage: ${HEADSCALE_NFS_STORAGE_SIZE}
