apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db
  namespace: authentik
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-minimal-trixie
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-db-app