---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-db-app
  namespace: authentik
spec:
  encryptedData:
    password: AgDduNAq8CqQr1IiXsIsReHdJt5e64k9Wnl0ipvK7bmEgC5dLtDRIEWwEeWacvKrw5oU9SHvvLDLaPwDff0anphKVbripIoCNBkMDMJiuoAA6FFL+7eDLzFblgi9Pk2MSqd71cDYw/QJ1P2ZM5C6A+IcLHLs8uiNbghgpxoYOXGIo/AbgaKbn7Kujs8nComYLSvqL5CZWw3VcC9t5O532svAlROBLXylxXufMYkHXbBeeta/0+vWRJuan1XSUZ6AUch/Uegps1et4XzK1ihsomVY9T26DRvPsLKK+E+JZ23zzft2GCySC6ePY+ihvOr+K1GJ+CggVK4wldnMN6kaeRRBQHwJiv6pqljGljNLL8adLta2rM7/E3cmsgUMFgEsc82klX4ZUEnsMQ+LEFVk/kPbDL2zeD5pEarmpu55nQHB4v8Wpv0sXKYwffnxmbmu1z8ZIwLs1Luw1Fi4IXkvkCp6apVQHl965HQpuKugIn5MpzT9d6G8/vF/y/u+4DBerDXmMKRTb5MaQVwwffzyHcmC1OZfWr/+r96M6RTFtElORDPs0lZS1479uhFGwF/cr126CTfYvvM46U/j36NKIddCIXx01mp1exuMWxil66GFuAjVZDjJfaBXWCxn2/Wr2drrsnCy1//i9yU7XvKuKD8KAg1ry99Gm/QZbRy37QTSAa04ecHdih47ovjRPPnEPRgYfUCIjYyHlW/gGohOr788w0HqfUfRQtIg3Y3ozvZvOXiiNn+jWPSnJ67Y/SAr9+bUSY07RwHvFmU1Sup2iyaODG8qFA8zL5WkjxaujGdbCQ==
    username: AgBwZmfIzosUyDy0WRJbDvQqV8O+aNNPY94xnUkPM1Y/Pv5ptjJcLu+kjt+oWyv3NgCILKDrNLpfWxyOzIUKNqUz0sGsQB2+2prCmycsQW9icTC1u+cEzTZ8PPJofUaTumorS6nZmwDInoSWLpRR+EKKF2oxZ9KmkDu/Ud4KlJ173o0Lq5CgP+MJ6gLUv9hkXUSjvyuW5Xpr4OlMrEl/jqBSvf18fUgXgINrJkmc1t0CTkjtjNr175Nin3spqlbpPxmmskKm22GCbphAklZsbG/JSY9anfM9pbx3vSZ6g9/AhDAt3ACKiyr+KV5khlV6xoftibRo6msDWqtjnyhFi3lV6fz6+9WRs9xd6JgMJYch0D9GK0JN88dgpoyP2GAwuZony8aNiChYpkrQxBTMn0H3b3Y/TD8pkey7osSRNZo0ZBWIRV+Uqq9CYdp3QsxGeIdC+Hwi9MIft/xUwDDHr/C9GA41a41H5Dmk/4EcNJ94NBWHik8+rgAzX98Kgwqt56nd1LU4ZpuuM6IsDBp0iO7V7TehdTDGM57H7jywMbWnA/lz1HI0SoiSINsHGHaUgix9/YhVVxa2TuPuXZIdZi4Bl+yDuJ3XRgXLa2TKyjgCCEtgXgPLiDAFXh2GvsDvex7/qSB4urZVm1Xq+Pu/e1ACzo6oB76RFWoOZPiDe4ej0/aQkthTnCzo/u9h8nyIdqCWj0E82kSNP9o=
  template:
    metadata:
      name: authentik-db-app
      namespace: authentik
    type: kubernetes.io/basic-auth
