---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-db-app
  namespace: authentik
spec:
  encryptedData:
    password: AgCrMPfkXKfb/Gt+FHrdJ3LlVZuQI2DwXa9HWD2jx8UNxKSi8bviaYk78nVqUadfkJh9cgoBSK6RV52ePDrRNjQFPXOnITg4zvILFdkhh/IKL+an2ziptGBJ6o2qeJ3Hsfn7Mtt7BGs9PzspqsFqOsuSkLyhhcq6Dhrp+2aEG0Kz3eczGhEA9EOkkDpCzEVsm94pwsioks1uUZbhIc8W7Ti4629J+a/PlTg0/sN9AuSpz6Hjs84z4SLZSPXuVqF5ZhlPZBagGbFhFLrp9bc0r5SzcaJzMaf9SWURGQXgal3a8Ppg/xNXkTwErjT8ne8Niz618J79jz1AhH+KIrU8PIHK5R+3I8BEyx7jrVU+R//WYhQDg4XOMPNdjRSzwbhTfv1+t1Of5DcbedjVTzZS3Qyd3S5HNIkBBLzyV6ZSExwUk5yMyDbJl2WOc1FNrThlZrewiOXu04BzS/mOZD5LfSYxk1UnZSKV4q1u9BFBuc/BoDnGNrn5YrDWMZDGj2dSacG6vHEeEilbOQ5peg/3AhqQ/kmnfYelH2Gwfb5nChOOHPM+grVT+tcNC8+G6lQSy2j4DymRIbWfDjaRz4nZuJMwY2j+gQlF3cTwnNDKjw3WhTqB7eqEbuLgeYVRt55STSdUkhQv+UOfLRJp+aStlr0LwYBJYPH/oZK0X+0iEVKMSiDFYL/+Zz5ZIvuj0uRoWjSwFPjDVziyu42FI9RJP2OAa2CLgXZLg2TBu9vEv1R8TfGmezkEq2OzXU/5HJdI2GSloI6H2asf2xfsqkwuBh/e
    username: AgBBiA7MDXRoAfOqI9W/Y3O3muicIzcmjzzZN9jWry2y01vmop3teizsTclHTNWfZ7cKS18g22MDwARSDx4kHEumiiZi0QiyaYoFnRsusjDwwhN1Y6+k46o7nk/2aGtWjCa2CkGhx22tU3q4kZfI3aSVO67l4WpxY9g5D6Z9p8umtG8WWhphmolcBGzrbB5pg33GdEu1YDxdCniALe3uqY7+nl6mmY+Kf8FGOVSy+rBgseoFBU/sJ4jIK7FJQ12rOJvbIMLFCwad8bcI4cz4dzC0FtXsSK2QpF01+J8oIVvaWKCAanAxepPBaPzJfLjXfIhTcgZGPat3bHa3XkS5PTmWRCpoeNIb5zwOpTkC35NO89Cc/vBBUEk0ixSi1NHFl4Hy2GkTNfdNUJ3s502JOlisP5YngFq+lWIYcl40vp630tO8/67M5oFGUqZbne9HAigAjAbSS02mtfHIyb6zcLKkpVi+cU6a13lJ+U2iic36tC8Zand1JzaBorWs31ksCyQUOrGFuilRnk52alPh+/9rfLazuGDsfAHi/sDbSk+0h1phO4eanVx2br+gzhZscGKx0NZm9F2EeF0MTM/zqoRNQ9vas3xnkv47HCr9TgWSmiodpUWZJo/OGpB6uX631uXUbhwcgi7TSxitBjk9BNgIHLRZEN9Hb/OfICeZX0Bh1L7mrWmUs+/4+9u0hBRaf37rhKu0na7wPmE=
  template:
    metadata:
      name: authentik-db-app
      namespace: authentik
    type: kubernetes.io/basic-auth
