apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://charts.goauthentik.io
      chart: authentik
      targetRevision: ${AUTHENTIK_CHART_VERSION}
      helm:
        values: |
          global:
            affinity:
              podAntiAffinity: hard
            env:
              - name: AUTHENTIK_POSTGRESQL__HOST
                value: authentik-db-rw.authentik.svc.cluster.local

          authentik:
            existingSecret:
              secretName: authentik-secrets

          server:
            replicas: 2
            deploymentStrategy:
              type: RollingUpdate
              rollingUpdate:
                maxSurge: 0
                maxUnavailable: 1

            ingress:
              enabled: true
              ingressClassName: traefik
              hosts:
                - ${AUTHENTIK_HOST}
              tls:
                - hosts:
                    - ${AUTHENTIK_HOST}
                  secretName: authentik-tls

          worker:
            replicas: 2
            deploymentStrategy:
              type: RollingUpdate
              rollingUpdate:
                maxSurge: 0
                maxUnavailable: 1

          postgresql:
            enabled: false

    - repoURL: https://github.com/antblu/antalos.git
      targetRevision: main
      path: apps/authentik
      plugin:
        name: yaml-envsubst

  destination:
    server: https://kubernetes.default.svc
    namespace: authentik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true