---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-email
  namespace: authentik
spec:
  encryptedData:
    password: AgCTHrj9Ym1JssznKVHLuiAqg9B0S9O0cTKDgqyq8nYdXwRwIh4xh29GreFE9CKG8pF1tY0eZS8XJenZFqNn9cVBWiclr0kLvw0OgVh5RhN7aIV8gD0hRxkmCqG8bK7O6ZDEAwiDuzi9uZcTdE9NYeDL28S37F2DI5LzmhWMftzU1wPO9kmb8HheSkTHYgBxZn/Hvw4uHr7nGVVQ/xDWaCzSTEs9aBUvX6BcT6VXG5M81Au4ynhWhEKxw4PlGisu3I5JsKJVv75Qj/IXLBVRTsTIOBlBXgGViGroz/HSGuuw4lF5x/scIyG9KVNsDqHSedUulDrdzi+XmzkmSkj0BMWcAW/nyIhI3ZfjV2PwNPN9RtFpqKeYHePOGArVKr58Wc8if9qCEHJJVpirtVIsXybbiSfhZo7ihXKgWZQSAw520HwdjNpYBT6GM3FTQyIrvtXwL+MsF87klfHJ/AYJBSn0HR8Oto5xRQxMm5kHMudu23O4QfZnN7XDqd2UbLkFuqQjl7m4ptnJpMJKB7u+0XOb9gEffzXQX0fbZq5zNExR4xCgr+A6bjhA/eY27a3/+fN/Yg1t1xZ+Mu0Y9yvX0bnBAw0nv/iH24bAqOEl5X/aIIdrCtId06QPuFU86eGxWQU2OdV7XjsrfGyvOwfAxbo2kiCKbB07hMGWl5p5zgktzs0HVxmfc9C/YTsBxKZA8dc=
  template:
    metadata:
      name: authentik-email
      namespace: authentik
