---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-email
  namespace: authentik
spec:
  encryptedData:
    password: AgADrWkd1nPKaVNqgS25rnZ5kdNuRAKssPetUsm8447zMHjtVsu98nClsB3YfDJi6VsCWH8zMClRAoaCxJl5/Qka2l/b3mN5NCGbUWBs8azDqPXoX78ChVDN1V4MXjPYrkJ6WUgnrFpIm5SEJirHJ8YjsWo4Z5g9CEHf1ZDEV2V4BE314IbqOLqeiSeK8JsrWGFV0AJ5SRtZKIqOc6aQiO+zQKvlynRyfgdXFfujjq9S+jQiudN+8Us57KDxDx7pTmOIju4EOlIy5XEZEhQ1OnYCw7cPm7fx/tnnLDRgA9RxY/j8crxznNvJnu/VZQvQOsJsPM/nkxB6M35JQ1bsosE8l+Go8hWZlYNCnW9fuL/qpTHYY14XLrFZmoa5XOwRDsC8gxS8cSvZSfpHk8OOEmibjgsr565kAgDBiSXGad2CFwPLT9gaWjSBd9aJ9fs+rguIrmn8cgWXF0eDvUTCFhN9Z9Ql4jc0FvG0j9SYmx6qsQranwEwacpgQo9EuI5xhilueioiY4vxbOUIaMUzKJIphmw76wqfdhrINJ2vsXA2OGrHvBuaxlCjPQAADCC1wrXstnpfHW3zJlIiSiM0G+IOL3/WXIJZui+TJTikiwyZ6UQIjVj3T7WHSm2JT0M7P++9MctKuQ+00Lq6b1SNOTiZ0KHtTGjEibLIBg2KOlqsso204+k0KaLva0ujn5NjK3rb5knKguyIyJ525kqkY77QtrsEhETi0iT7ADvjC81KS7tSew==
  template:
    metadata:
      name: authentik-email
      namespace: authentik
