---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_SECRET_KEY: AgCuhsFCc2gjG/wI5iEU0yaDe/1ZdfHvPXtNfZKZWbEK5ubwhjRdC73+RGwa1CBK3Rr1TVkB7h3X/4mBFJYjJFhISzbwLW2eDX1RckmqSRl/U08+mHEBcSfq8PphhcYJ0S4IZrsQAvDTXKtdgzqd4qq/UsU1/xCJxJGlM/WT6sJh7DA3dkfQ7WW6Uy7VB3sl5+enrzJk5e0CCU38enqg7XxMjN9soAexi7G8dO4FWSNmv5XPDqsMSy/9JjchOGMMD1Ba2Y06ZebCOrDYFGM2etBvNR9F0rHreM361yzUpYmV6p+q/AQO4K/YaaZ0tNkHPNn3DGzkkQV4OlcITbjeX87QDxAD0voJ7crjZ78ETmT50b3Awm8qcWKe46JfBSmG7wYXpqtW4n8stdWCOrS5UEFl440VvuiD1uUeuhLCnOsh21wPj8Z0D2D1Cojt9SIHtxp6A3sg0E/bDpMoLu4Yx1OmlXMX4irALyoLZEO8MC8M9AAG99kCZDBRt0fTw29bSOLqAoTzqVDXUe5woQhJ5jSDg7iKwanjS+NhqQONS8yyo3d2uciedcBeCsbbM12tY2ss3v0vntqx77YaaT4tlmZezD3G+RUSbURIkSXGxTLuld8B2R8NNtWqqT09zXKdhn+Qqff6E9JaEiYx+Vi8LhF7/A2XiZFJpMTxgnYAZLAvW9wm0GETAIRxIMKf5Wc+o0D75kG2WpWKoP+fRC/Ws6mCVT6QX6TmsAtx4wVOPt83LNWmCBpMCJuo7bzs24xCeI8aKjBsV58bobDowclNu+4zcqAyQVvPJVIOJSxIJx2DYINZxo23HpoSGBvGyacEY4U=
  template:
    metadata:
      name: authentik-secrets
      namespace: authentik
