apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: node-red-oidc
  namespace: node-red
spec:
  encryptedData:
    clientSecret: AgBzFqQyUC+p1t1uGznYMmNeLoNspAcdnM7wnCp3lrLPOuXwW7XFGNMqSvgD95d3KFoCMNqxf/WqHDwqz+kE+ig8HHpDkVr8mmA4tKSoNX76Dfnr4xAIQHGAI0utuDxIg/HwDjUY5M70XNlCAsY4BPBqQEsrXcHAZXda6RC84Vyg8+ODnOimypHsipUNSOfh8RAhdlJMLUjUpFk3HtoLusIKItfiFOCzVZP9ipL29BV0uo3yovTrht5ODsnPvG5x4uH/1J+MUdIx9Pz/NvvQe7l1SjIJrlfQhcioxTM3urMVStD6um2fXU6PIam3NcTbhx8TmZ1Pc232y/sroWqfcDIgboFNX/S1piC8wjKEcOi/pYJ2Hy4TgZZTKQMYmXIrUL2LSlxM44e8CCmw2wfmGFKPNFdzPbcvuvNI2zPDyyUm3Fut4fsY3EYbo2IPUAWq2OlhxowWoKOjoHfvHWg+VejfMtsp9fLTdCV3h2hmI6eomaAkMHf3k5nyFXcWkaaKOu24tnyluNc1yaGO5R+9bM17HVhJAYh5arDpCpwZ58+fDutukANl3t4qY2k+blQ4Swq10X2Sj6iA2e6Kjiar7L4a+fVZwLFkzTyLOpAWVEAczgfo3LfpJ5nOrIWacLFhVAdRjDYyzMXJ7YVXwiRjItnFIBLPpfkZVqfCV98nwmBlHBmH5Y740D7OPdnYktcrIFrq6jcMtsWqJ7GtctmD4HBvQ+doj7SeTRQatT++T6g0D5G87ELQXrrEG1MLRuf99A6VsjdXc2U2WqJhw+ls9Drfwo3XPz5pGRmBVzSxxSWDa/0Ofq0fujqIsCpgTCSKOZtZ9JSao5igkkfgvPj0NbFi8TMlMKhsZ74N2s8krTefvA==
  template:
    metadata:
      name: node-red-oidc
      namespace: node-red
    type: Opaque
