apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://bitnami.github.io/sealed-secrets
      chart: sealed-secrets
      targetRevision: ${SEALED_SECRETS_CHART_VERSION}
      helm:
        valuesObject:
          fullnameOverride: sealed-secrets-controller
          keyRenewPeriod: "0"
    - repoURL: https://github.com/antblu/antalos.git
      targetRevision: main
      path: apps/sealed-secrets
      plugin:
        name: yaml-envsubst

  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
