apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: litellm
  namespace: litellm
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: litellm
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: litellm-redis-data
  namespace: litellm
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: litellm-redis-data
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: litellm-redis-sentinel
  namespace: litellm
spec:
  minAvailable: 2
  selector:
    matchLabels:
      litellm.antblu.net/sentinel: 'true'
