kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: litellm-db-app
  namespace: litellm
  annotations:
    argocd.argoproj.io/sync-wave: '-5'
spec:
  template:
    metadata:
      name: litellm-db-app
      namespace: litellm
      annotations:
        argocd.argoproj.io/sync-wave: '-5'
    type: kubernetes.io/basic-auth
  encryptedData:
    password: AgB0DX/1T0cGY22eYhmT5ckfAfOxDdniKE2wp29kwg5tQRGXwzSax/MlOAwG6u95euEQIea0HeVfqUq8XOaeM2oY4EE9U3CaxhS4UY0qGX6ley6pjtAsl8NFaB0u3wVM2/NqmVGXf/sdGAP3kB1s6J+iFhpzm+5FaqYzR4LsyLZrDQisKF5dKZoOyvgbhlBiOky5YfQXgPvm27q1u1YK06lYf1VM3qVFIpNSowAAMtwz/EwI/n6CwQvr8T6ZLpa3LHeETqvneOCB45WdYpOt5iYctxYg+I+ksY5s1GbCsQxsI/UxvYJ4E7kAX3Lxc6a2De8/m6LbkkSPGJFEkJQwlsJ+C3WPST2Fp7vJlcgxqcZe4cL0pFmM0+AZKBxvWXnsg8Nvij2qCiQpSlFw+/58eablP6h4ChyujZ4eS4z24rpYqDH6jOwddFE2fWApF4utYGPytcgssNqok8wCuATrVUWoPelFVBBIBXPisfE46Gs4/sdH8UEqSZC2Pst/CuNTy2sHpKIhU8+im1Xuu+6zLeuIq5KMUvVpcqtD1o8hhidNJUzATgncQWpdmZypMG4lQT2vK4rlTIdDdpuAdlck5XDwj4Cwb+yy30/AkqO8LZv/ioIOsukVhwGqgS7ggDoW/Xnmzsv0qBvEvng7bJThUBsyhckdF08tEijfyMBjXcRcDQowiRjlMSzUkgKSNFO0Lmwzt5O97fgSoKoPz/K/wUkIQy/BPwao34Aso3h2tIPVZ5K5RvqekOy9uyLYP0eOLQPjuQQ/RT2CviwBhKVXUNcH
    username: AgCqNIVGbgTv/NAhNRIjG8BgoQPi0E/7iygK6vxbhEJYZNJ1T5MSk16b8hkl4CmYK5ptxB5PukJfWn1z9hPH//cfuFArPyfZNFxK3WG85ylfV2SJV8Brkfm4Nld0JqU+2vVbhq2v7lssiiLg3KcAqIE1JSnkMm1Ooq/+aeXcQRq822KuHPSPDZIHNskzN5z4QVxL7Zm4/nCg+UOnUrxF/1QxJYB+6EVcBYdjTwhShkrBckgyKJN9l04dQ6PzFMzBlIu6OqKUkiE6Qz6jhwgAitusIumUi2ELtBqER7CO4EUXAnyZF1jVcXFlo6Y9YiS8ihb9XMRDTUXNTgBVFBuoY9ntz2mAZy2LciR4P1VksvI/nUrKQP12VBmAG45uYdKFjXrXlGH72UoKrtFsITREQ7sSisY8uOLR3qLt7Ch8dePLoZDeibVFsF7HQc2arR5cfDvzi34a8OQ5C9U6Ukyit6x+R2nzHgZzQ+Fzt6p6FHmNMrej/ax6sE2GzIHRFVHbWc2Ht24Av7lRDwbthMep/xDp0zPnQ3akqvmMq9rT29zNBLzYVCrrVLqtYe80YiyfqMLGmS/wTQZQJMGhHE/RQfY5kYHl3J7V0t5w0yisdvzpHP1JNAzmMAZ0Muu8EX2NFBiViI/T0Ukf7KdpQf3S/fpt7QNgEWtb49+EQA1q1S1eTPhGCwI7qWq9vHwEpKi59I+r4hz0mvhq
---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: litellm-app
  namespace: litellm
  annotations:
    argocd.argoproj.io/sync-wave: '-5'
spec:
  template:
    metadata:
      name: litellm-app
      namespace: litellm
      annotations:
        argocd.argoproj.io/sync-wave: '-5'
    type: Opaque
  encryptedData:
    master-key: AgAtd/yK6l24Nxdd5uriDOMkRFL4LF6v4RSRu/X7WYlfAp8Ycjs4pGTrfnWtrrEq3FW47enMUNnWty+MGPY2c2ZueLPQgx9MPvWfh1kXgoAPc5Uwk07CHXyZ1Eru4rejV6Q4uy2GrpqPMRyNGmiPihEpA9IwilZuM41UF4SMoLqBWKIeZmP62ETNE7iUXNbJMwwWfbwn9cfkl7s2g1ecD9MkgX5jP9SnjSQqw4Gq1/4+M4JlLhPeIlkB1b72mTjBN0/hvjVmLIqz61VD7QpGRqR/5Q/71fhbjK0SkIQRjintwhPhy5+5OIEBBwChd1Wdf7PvYs/GqUiPM5Lgfw2WQRreCkt8hBloKZtk1Ri/b55vcSpnIdC4xCRYuBCj2rp/kiPI6P3a2xivegpaM8mT3Dxub3L6f13BHXJl4qZOJ0XcT5C1VJxkyR91m6PuaVlwEyBD4wWrobcp0+GY0P5Mf80XEZfG43dV8zrrQiE8NuLOxb+w+U/2hOUDy9lQDVESkFYZ6B/igVnt+Bo+H5nXu6w5ME+c7KxQ7XysmSgO1JCFI4fBOiQ5wN7rmEiOOG+Wqkr4KGYy4oZuJ2Rh3d9HIGsXNrNY7IWldGYjeBVZBS8hCOurDlTtOGgakwMX8GRBxZiMPn3GMAKAq2wlS0loTR7rVKOmt7Z/ae3Gn1/O3AjHg0wXHVPfnhgPYKrYnkrmE6TGDO4cntlOLPRJ1Qemlz0ABF4H/yQDgvEqhLjXTsY4Kol1es+LjzsojNYmckeGqFAEiJBFB0dkwA1bN/O4ziZeW5Up
    salt-key: AgA4YbRuh8g9nXzBdrasQqgPziks1ir2CSmLs4DvI8fnukkBic3Po8Rzi5AHb7XlKNvad2IROR/dqqPujL4ZkgaGuZB7AgzrDysvPG9S2GCTaexQ5kOe0MXGrdfM1LLgYS90jFxGjlvm3yOjixcwnqrScT0sJ1WJe/YMksyu39sgFsPBtIZrC24fkiZwL/Ywz5TiViX5RykC36miwKfovDb+yw+tW2DtSQG5F7P8vEYmENiqWcFijJzx87czt/9dSNyM3xgg8H2dYB+2kXkdUiGA85MEzpgu9wgku1CUAl5lWRU8YssM5SnE6wwVhywjzICIMvyNg/AVleRAr7cjB24T9Sqogj3+MqqRvbKBSmg1uI76uARqaQtQS88k7qrSdvVGB95TN6c9A7afVTTUFohcgGmTlzRDdV/awiojAsz2J4Lvb5j7nquwso0+qkx+luUPZaGGLhOeS10PwuUSXvcNWRqDs0Pj6aVYmskHLtAyT9dls2U2P5ZzKZ/aEzT4ifkk3uuVvLr0cv6onPzxhC4FedjPYBPzeY43+Fp+4JDRsunwRnfD8SzZJ0HX38ySdMQfU624tAIy6KfoDCTe9WnmR3FkRNKhrzmcG0OEfCZfDa2Xs2t18GnAEHWoKBYHBveblWbesWHkQ0hZA0CaYVwGkV6/bC+UZ4Vte5+wrOjt1Pb3JCDV2SViL8o3EjbnARU3wGC6+ruYPf8zhvWkxrPc1S7iO6pYylMo5AXceg8kTJbOoJ9x9kcXsZvleRNHAH1qsGERD9ZWglqmz03pUfIT
    ui-password: AgCUHp+AguUvBN4VvTtSJv8KJmTslZS4h0pcp2C5u4SsaZl5suWIxNTvr7o2VcuoaYPXVe9efui6tehIwC6CJkZEehklFwJxZerV5mPy+9HOH30qrApMXbRs/9nQADib7D1PGuINmE6ftqtiDdV/eXHtoaMVlKnIjlJmduqs12P6ohXziEueneNP1jb79O6gBX35NpgzrGFIljcO/jMpN7+7nJV5nwSrVlzfvG6GA4nLnLUu0uSHSv7xzqJZjq/f/Muis7ylfjPS9XpLSMHXAMkb8HDO4iV56Jfg6LeHrePSr5VW8Cyf75n6Cpr1zLMrfc45A4rdTs0IKztqDBfX9DSCAnHLuBVIu9jLFtvf+yKAaqzb/9DCR2gxjx/FAXzSI+ZWRmN7uCY5F6uFk3q6qmDjLT/KymKizEY73PgLZILyxhUKKjlsOl4PFBkNGi+luw7W32Nb8QZpWxUCrmiwwMycoB3p/py2lR+xm9VP9z4LqXvAyTmftIwRLS+zjBJWLcxis12kcAv39dcqH1DkQZApmThZZVQi+Vzf/LsYq8ryxfpQxrMda3+Yh4yjN/ZYH0Yl4WTqD1eBeAAC6MBfDMOMOwE7iBHEPNaFaKNRUoSo3LvLN/JomMlwKYxnC63EByW4w8f24e39KEkXk4dfcnGZ9Af7ArfI4c+mnYrQG3Kdge00Q/SMKuvUxXzxNLTCVPy8mFYwa1sdktUQ+sG2gz+Bt/iXX0Lb9GsEtKPhYkIMqSO8oIxVBqCKfkwQFDHA+cE=
    ui-username: AgCJ/K965iWFTIzOA5SJc80y5p48vBMDer9xa0hKJHLoKikD5UKEoNb4nj8GD0vBHo9MkjGbUcSX3IQV1cEQwnQMG7O7KREAhxkq7woSmOL9Nt/KRsXwbw9xZu/OSK6CtH1ptA257w1SsV/NFeMGoh/HqOxO095K3KPcOc5oZIucbB0ky+fxgXj6H6PGVNyp4WaXd3F7GyerwLgHQm3YtxRPOEl/HkJ9B2IyojgNSa23qe2AedPctZ3imnKxYVMxrC/I3J5xiXYVDALQ1e0etLbU3SYmhH9pQwJm+X4EWdBhcFvOdq10G/35g+OzT1mPLN2XTW88UTF3Eoq9Vn1hN6kt8LZq/NZopq9Z75nDv7+wy4PLufsU2rStnf/rFO0IUoelxGSVN2kKD5QgehhIpOc3XROCZCoVPYbR9rCZDCq69J8InXsweLxRIbh/cZQpwUQuiJxd8lFvZEMUwtnpnnTgB/4RhZUqOiZ6XbCTM20KUT9Da1jx3N4EW9LBEyrdTyZ7BSVE/yPLa9qsQ90xgYsgtT4tpjuEtak8T8gnV+phWpu+Eq2xy44KU7vRqhAZGkjy0Hoa/tfEgRDcMYVB8k2jP4L3K+ssSZhsw0Wt/nkOmjY5bGtsxdm7qYEpV4nio2z8EY58APeEp/GA5q3Y94WqSnTMbA9vje/VrDhv1tRv7eRDnMYBzZQwQYR5J587uL0TDPXUjA==
---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: litellm-redis
  namespace: litellm
  annotations:
    argocd.argoproj.io/sync-wave: '-5'
spec:
  template:
    metadata:
      name: litellm-redis
      namespace: litellm
      annotations:
        argocd.argoproj.io/sync-wave: '-5'
    type: Opaque
  encryptedData:
    password: AgA66DPX7p/h0TSk2133vtEEMMJNASePmTORNURtSaxfTt/sWnclgYHzVQm2kk94cCN/BteCfY0T14bygfJWa7veWEyFhPSvnTRWbEYq2msfztMWZ8ouCSPu+JPa3FgRoXWK1GEJVz23deOXig6ezzDcwliFifZCJ7IKdt9mEUWufMbrE1Jm+w+EjasX40flA69hiDJRhbaZmCMtNmAECYZcHW2isqiLOakh5KZqjFoDMRDmbn5n/bl1JqlqDL9TlTnoFuCZH2YWCLswuXwqap6CRt/pOuRqwsA212DFo8jbT9suHxbjN4NPFr+xN3B2UNEXv8kol5kV5MUuPHqJzI2X66bGdKpQO4PVaAQBTqTIRlBgLKAL0kDkBTlLcXgYHKBRolQ0UJ/2kk1mA59lLVNkxdfORtvUwQ58Yx5bxAGVV8M6AL5O6GMXKpa7Oj638c0A3NrCNNdABie5KXIiZFh8awtAEyK8tz+JpOXXix5gKipFZer6Pl91/fuoLfJU9tbzpqsQNhJnQEiIyjKFG5muBGsj+731devqZVErGuHpBP7yTqj8Cx8mzMiRVro7FfKaURrQm//h/S584x80LQ6wRFb5Jt2NedsaCwCn0EppFY7rk+1fOOotve0+ZBIbSrGqWdpDz55YRB1we8aZlRqDGAIhZCXAsRlO+IJP2a5Gpxjk6XuahIrMyEFtxvTBmDNPQCP7CigzpoAIaX4Swn0TTeCzp8486OEN+CCANKvxg3TBPnXRliCNnqdvzfIKu+QO7Eej2hbyBjR902jIeiAx
