---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: obsidian-couchdb-admin
  namespace: obsidian
spec:
  encryptedData:
    password: AgAIxZ7s3bvUK1mmSaasbMYsxjwV9V0jxj5SlOnre83DD49L7wZSU+ycqlyNCma/cNwJmpDVkJAILJrfudlta4pLx4B9v8ZUY6FwFLs+7gazCsfU7ZhVUkDdkgU+4fGum6SXlB0NDYw6Udb+kV8i7DgWqI3ZDRPr9tOE6IiZj5vhpbyLibuv3n9MF5GFj6i8Ru0oQUj6Q4/MmuJJnV3XHyhWYTjgcc6o7TUKqTHRjzKzoeYSyU7D0fkf2SYRLnOZHMN8MJL1IFZ4RNcF/qwDDET8uXgMbUir2Luc0JiOosrS+csqIUODhHZEDryrhD6QdEwuQpLHg2ur4neJDi3GBUvKh2JKrSAoxFwGZKU3yByp+JBR8VJyU+kCltEfLO2qQL+9mC0weSppfUJRPcjVsfcbOVyjIu4SBgrLjYLL0s36O2PdZBej/W9I/tCn2geOdYbbGYHwo5T+8kdX0cRp3s79HE5wACu1PUcFqwE0kUAafcS3lfnr1MM/fF5v+HsxV537/nofyomKIk6Az9w9Au9nuqkQivWQyFdzF8ZBanufNlqWfdFh+kz/FphFjrRP62TquxmJ2qSYJzLD8R0ayk9PSJZLuZmB38WkJAuGg/0r7+Zd6MlRxeXnhy9s+a/mOYdybneGgdOsDU4YirG2rrInIbt9581y4WARiYrESBd+rTfeCZuwjHFLB+HC7EFXCoyk/SFa4cRv7nNZfV8jwKKwvasIWmCBzjdg1ouorEvcr1CA4N0CM4JL7GXM+eoJsNY=
    username: AgAJrd4JtYEkWQGHrAyoJLnHnWl0ViDoQiCdavIJgde+J88/38wzHfACohGDAMmb4qwnHLOQysI+6umPwp7KtYwFZ1nUQkyLLjvI1Vv9vW0F3xaMYcwmmZK/5kVJftEAvGnhVebgNXbZFrxaN1Y3W8skfTIsYpDc2Rop4ArwK5rU7gWhRobxzWGdY94/pr2Jf4OKw2/YOavxPR74DZGikcNidE2tZLI9QKV8ic7te1O94gRI7jwwoCweq4GI60UlKszCGUC7yWMSPH4xNLRCfODOxRkPkuIIk3W+LIdgpRgQ2IlXCqg/U6MF69nMbKMHbnE5zP9qMO19Gqy3akPxJ694PhF1wsD/qAWzRmNmXIHm774Zv+XGnzQ+WEChA9hJfgbxeNpT/S7XBi+17Ji6VTu4CAeSm7nNNP9qFghF+WWnoEXVRQlmof4bGDqJa67hvflCBzaVWQpudI8Sz5oslRl56wTDrFGvIgmQ6GhEYXfTUjzMsvo098YaqvOTyqDaX4S5PHSYf8w30zeyuGMS/AlP7XvtqBYH4hdcUPc097DFPu1UggKWNNrqc/di/9v1YGu4o3dkLxaQgbQhBiViGvEHEKIns3oGC+Och3SOaps/IO0izOrpWdO8zLXw1mUc3wmHuSSIsRdyGRSvZkiYH4QLYAh8D7BLY47jtiKbsVPXw0t5oHXjFYjMUI3sAqj//7eFfdYi2axqaI4TfAG9uA==
  template:
    metadata:
      name: obsidian-couchdb-admin
      namespace: obsidian
