apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ${NEXTCLOUD_DATABASE_CLUSTER}
  namespace: nextcloud
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:${NEXTCLOUD_POSTGRES_IMAGE_TAG}
  managed:
    roles:
      - name: ccb
        ensure: present
        login: true
        superuser: false
        passwordSecret:
          name: nextcloud-context-chat
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
  storage:
    storageClass: openebs-local
    size: ${NEXTCLOUD_DATABASE_STORAGE_SIZE}
  bootstrap:
    initdb:
      database: nextcloud
      owner: nextcloud
      secret:
        name: nextcloud-db-app
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: nextcloud-context-chat
  namespace: nextcloud
spec:
  name: ccb
  owner: ccb
  cluster:
    name: ${NEXTCLOUD_DATABASE_CLUSTER}
  extensions:
    - name: vector
      ensure: present

