apiVersion: v1
kind: Service
metadata:
  name: nextcloud-appapi-harp
  namespace: nextcloud
spec:
  ports:
    - name: exapps
      port: 8780
      targetPort: exapps
      protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: nextcloud-appapi-harp
  namespace: nextcloud
  labels:
    kubernetes.io/service-name: nextcloud-appapi-harp
addressType: IPv4
ports:
  - name: exapps
    port: 8780
    protocol: TCP
endpoints:
  - addresses:
      - ${DEBIAN_ARC_IP}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-appapi-harp
  namespace: nextcloud
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - secretName: nextcloud-tls
      hosts:
        - ${NEXTCLOUD_HOST}
  rules:
    - host: ${NEXTCLOUD_HOST}
      http:
        paths:
          - path: /exapps
            pathType: Prefix
            backend:
              service:
                name: nextcloud-appapi-harp
                port:
                  name: exapps
