apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-admin
  namespace: nextcloud
spec:
  encryptedData:
    nextcloud-password: AgBu0ZUpIQG2nkDuTQcesijXyETlNVDf0BTlSWgJ4VH1ZauT9i6o++oVyq6hEcZt4dYEyIU2nDVC2vwFty4kjy5DqLkVm5kQuIhfHmKozk9tAwbyBBpsxIVvj1GHScxJXUJHB9gR/7U6MGXhw/NXXvY7RXvwYZ67snj+nOe1wErr7MwLu4KT1DTASSUY1TKZhPCy2LPKJjAluULkehLMAcKMyZ3y9IoHctjT4Vo3j0hkwy3Ld2bD9EEmXjkxuX4FUpU5BBVmQpjiSfPFSAwNVSNeFOPHi6YXSgUl9MdfccsxlpluJtpLO2UCIV4jfFZLw3uVQCkEh8mza3W93jH1r6t1BZLHMFVg94nlKBWBor4L7g2xytWmeXUs+Z545ZNWeHvLYz65aVVJ19MNgm0xv14mFuDlglo41l0rI3ce31TY4zdCnLqzxCKWnmLVq6GzyAtQD7ve77lmECisPSw1gxqoHj+afusDMY0dyrTJ0pXubTIO6M3+MKmJvtoB1Dv7Rhe+d2T31Uh7Vb6dg8nSx0VBpGZxeIUWMoNls+vzIEAk+rhoHd7Ts/55+MENMAZwrF357D98OE3vFg2P65Dae96Z4Ugecv3rchtSMFkIzQQYgfDb7e484fxWfbNKZQGcnsSheGyJ5dl7F6w2TTBUW0PGcuB5ThADIfEg3cIvgidCSwvTqqLean7ayDVARKJVaRy7EhJi9SP7nvR6piakaZ7xpykCe1zldcoojQc4OZF4IYtmDyJCr3hKk2BuwDEwaSWBoJXnoc2hiYS6zYMfehJU
  template:
    data:
      nextcloud-username: admin
    metadata:
      name: nextcloud-admin
      namespace: nextcloud
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-db-app
  namespace: nextcloud
spec:
  encryptedData:
    password: AgCqWSI9xvcOlOye0eIT6GnifNXK56OalsRny7j49u2Pv51nygNFUXHFxTFmg4a9RxGi4/LymF67imhuOcRBumYauuSflDryPeoR+cHz3hkA39SlrN2JF4fqi77mQPAlTs3rbidwK80DhxKJAdM+6szxJIBVD70lrKKnrUsYyJQ3Iad7uRy+c7Xk88h66vuh2hEajKP6wkayUip4eQjQxIl7c0dQa/x5AF0/TnEsgkUcGD9xt6KWU6KhJHWCuA3GD3IBSrRgS+Sa+rOFXbJWF1rRQ1A9J0mNlekjE5NcB9/7eFCDGYK4rvYGLkUtiVbxOrc/E4eoH+XLiFeyGjctdndgXiDBNe3sD15NDy2pB63jlWrVI3Ncnzh6Wa+MeowLnNE/OXnbS3Ub8AT+Dxqc2XYSfw36O/PUpnP5pCkb29cIrAK018SwKP+nHWQfxCQOqgnc5WS50dBWyOnsEt7mg0mOptSghjX48YqB3xdTnUSRLK6zscir1m2KpEaqwZanpUwbzDMx00JDrGxgDnNFWxG1+dc9NrLchRxzllDhQfWeCq3i8BdUO2BlPG8X3rQ/xblg0pODxGyZ90amRBiwsUUcQEirsI62cV1dWCgCG1e5pbDPUHUrOo+mCLCrPV86kV4OJUQwfT6RnkslOHqfVajpEGE6gcypRHWB/ZRBnfJbOCTZRQOIq4jojCS9vP8MBGQHcHQp36BWVC2OO5GQatTU/QAtFot6yKZzE3MjLNWJXLf18oVpjRUnjQkmTCAwHZac1Dcg+zR/FhI+qQidJ1cw
  template:
    data:
      username: nextcloud
    metadata:
      name: nextcloud-db-app
      namespace: nextcloud
    type: kubernetes.io/basic-auth
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-redis
  namespace: nextcloud
spec:
  encryptedData:
    password: AgARkxwsGbTRQ+NbSzrL4FKqasr8RxXoK/Bam2lpxbkikX2/02VpZbziRyC1YB5UvORxy6A50mMFBTymQQ9oCI4aWbiij/FO10LKvLNFYkMb4GjNJ8kjdN1ofL3USoWe9gDVcF7F9gERNZw46/qHpPUb7gZfNVpK8WhhytTOUggb4cXssJea+NQSIKLyFkB9lTdKoPeqwyafsXrhXY3HOyYWfS6LQOOJ12XgpzLuQWqVMIlUc3MKZvHrVHtClWcXO0Go9QKRTKEZpuz4W7P7O169hIs2QkGPER/ueiHvx8/6tvWr7pxOfRRv7jQlp7/4htizZy78GW0WXKulBpgwBrmTvykr+NQbeq6Bmxsya4iybrfLeRetxJw4TuJEFJxrHc8Q1+RmsuA3Na+hFmY97WmscPLJZnAjZrrbn1QykOQ3XfBD6B1yQ7oRLobiXtJw26rjmxeOQJ9YXVK31/i48oOXqnU9AJyWQEdcqLnFA/YhDQ86v2nw9uuR86i7JtjxLMPRQ22k0K0R8gN18CXFvsJ/i7Mw7FqJ3G4+LETV4xn0jtGSwwghLR93XRk9sa50NTKodF3FUGxXeoBJO4w9rLwix0PPMALAlG6Rs7PIhjBsO87xCfiWNkIb4Wr6L8bp7nH2cWnOX1CuesUU0NF7GthB7k0OUHdesV1mjvkwzlElGhOW3f5txsdqzjrayq1UY0unE3vtWS0f2eIXe5K93BZfVTWuKZkXpqaWQLhjAplaBw0ff/6oYOx272AIHWRGfifAv+4U3KpYnSu0TDO2E06k
  template:
    metadata:
      name: nextcloud-redis
      namespace: nextcloud
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-config
  namespace: nextcloud
spec:
  encryptedData:
    password-salt: AgBH9ds8RQtx09CAiIL2PPTTNQw7wxaiFR4ia1iOICMPf71IZsuZetOycSVBab5L/w7yWZlcjqzfvBUgUdUn/KT1RIydNVHHlTb93ZbUx1Pu2rxstCmmA7e6lZsQU5DAtgSqJzCIkQK9HJa3nAraIpYfbAhPK/n+BA1xyp/7hgiq9wLb8Td6kCCEmMJFWT0guiTeH88dy/pwX6lsG4zfDRnwEvO7It9iPKT7kSWhSNnIEcFlaPTRsq8aPz12VrkwbOWc3SZPhwU8Sulecj53SYRCDo9Co1Fy4MyuOK59TkbfWZVp8LzhhV977CO9G6yhpcY1h0nPFtGgm8CH7Kk82uCuDsmvwJ6PQJQFncoBOBgxS2wCQRbkCgPavBu/LZXJuW7zN5MkDr5ygzQ67Asj2JI81o9wpXqYiRi9/lr+FjYJGeqBGzALXkrRUDKpjbRFVPfViYtBztVNuy6V7A0fEll+aBOQcGuH6XxctWQ//xMF3+RYrUpq5v21BrpNCaaZVR6LUbLpv8VuXn5CZgnTeZNbKphvGXGMq7N12JL2u/+NRDKPTWKQ2Xb+qXw8hAxy6IMlqVm1w6d5ooEoO1B2SvCsqZRnYZoEUW+EJPHj2fHkJ0iWWNiZqyCh4d4WY/4ci4i1dpRMTeTCPDu6Ih70NooumjJEQssxKehvALDr6m2pX2QkgFMSK5oJj0nXELPv+2+rAnE5FAkqlKNJYsByBJD5pLBBqU7sd20GoAXcoVM=
    secret: AgAuam45f+RIRat34sgZYpthIye35P4qc7aus/uFYqfoqhBBDHo0VIHv4wd1WgBi7bJ9Sx4PyXgB0kaMHNiHw2t2OVqOu0/or/0NvAjqfx66fxI/UOLZzDale0ss1wXNaX27yjVIVknnCRFC9ZRDrVQHbVvNeVr+6RGesYFM153fJNS8XxRJ61n63Pe5tZ0vf3c0yDRYm1lQAyHtFYLJmW3iI/7huQJdvWHhMiibe5LWOF5RigziZS6ONu/+IKQlDT/VPNlelWv3bjgrfP95Ohb/tUsyQqFqX1mv8WgjSZH7W6Ypcr8T8hWvqQdDDSutE5Aq+azWPGpmwaX8rcF77GF/7H2uJQXriGspxKQWdko28Jv665osJ+XKhT477OvK7B2AShDssO0/xdIl+Sf23RNfZ0UrcaAmZ+e4erefHtGoHi59aEg3N/vWmPUtWoX51KfSITmbw2Al+CZf5H3CvvhJSUVFEN8otHRpOd7GVLRGtayNGMzAswwEXI09tjNKqKLc7Uw3jTacTtyt1j5CxoFaK6EbzLO/hbe27MLYFHdpT9b9XnQfLbd8m8lg/zOpOqbFDqo1YbGDGIUlSlRiwjr6AOUH6SXZXdmk7OaqiEDeBZoT9cHpTw3y3XJWcpNVpY0GAZbZUlGS6YeO/Ne/idZMAbtSzX2+xWkqB8OHUf4/Bc7FNIQNMHXFSPtowHYCv7QCngftJNrQic/is2V71jex6ynyN9i9W8nUOd/NZWvjAduoOSbwIq/j/tcPjSM4QO4=
  template:
    metadata:
      name: nextcloud-config
      namespace: nextcloud
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-s3
  namespace: nextcloud
spec:
  encryptedData:
    secret-key: AgADvUJhnxtrJkb2wG/bet0x5sT2Pa3R45bld+Umcv1nhJo+4xSWtPJIvgeJ+Rb6NdGNhw4AA9+IvLCwGOo4iVp4fgBgDlq70jIlXXuu9/uz5QMOJwU964rnvrl/MZSv7VWTC7FtXXDToDNyPSjjYMKA9ibMMYdROrYNk2y4aYr0lTwVzeQ3X9UEmPg7gHHXtmW3RKLCWdoatDF4QLxJj0QgWwIM9HIqF2TLqsDeVHAWzxQNfPuyAiZKUWPKsQSE+YeRZJUqrLE+RvzjRtMhL5NMZTEfJM0WH0+Nr4vA3/6PGtPw6fC6vfjgKPoXkxkyz3WygdJfw2c1BUpar4W7Sg81e74pz9sTjbdY8l084HPBYfVVsrA58bY3EptQigpW1aP/jcBkfBoFyOcsRkWJg7fWkfM1NSxbY37QvVaOmSQdeqi2nhWFQAlG6pTRu6KZ+8E7hX347FhMg7y57xvirCK9bsKqIPojUF3OaOZL9CuwGnxgb0JvSADr2UHywgseIaPknmDINIIhqQt1cSloDje/ddLyJR0PEEQEP8UWSbkKNJhar1cquntqYnRWVV8C1nxhEcxdvnMFES3lJI1jDxJGwEqe3kDgcKb/BmmguvdJ6gELMk9O9ekTa2208qM4JXm7JHLwCs88dwJOM8F2vbm81DMgkauFpquFVeDXNxyBfJ+F3diqrgoVqO+xvAczKpFXWZiuS2qBhSf5gSFkYtn45s0leSsdI7PvMTWD2KZT8q/InbDbNZtG7wmk9R7kyfJCpCHvtBtQXwfxnYxxUHaA
  template:
    metadata:
      name: nextcloud-s3
      namespace: nextcloud
