apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-apps
spec:
  capacity:
    storage: ${NEXTCLOUD_APP_STORAGE_SIZE}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=${NEXTCLOUD_NFS_VERSION}
    - nolock
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nextcloud-apps-nfs-v1
    volumeAttributes:
      server: ${NEXTCLOUD_NFS_SERVER}
      share: ${NEXTCLOUD_NFS_SHARE}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-apps
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: nextcloud-apps
  resources:
    requests:
      storage: ${NEXTCLOUD_APP_STORAGE_SIZE}
