---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-talk-recording
  namespace: nextcloud
spec:
  encryptedData:
    recording-secret: AgABkg/ZT40B1o4c3EzL43n2VDKdwppTb9zVUPrTNhWX1rDsTGEaSWzSn7Se1Yq/7Y8gSRDiyPn1yx4vTOxzCH1pH9gNxNHylc5beJVfEH54loG/CuEdJzjUiB130bSUapQ2As/3y0jZXAH8i3UCkhof8XetvX0rTD3l/C++BA23QaND6NG77aNYPlXqkdtlzMrtECJRL0sM6dBkNuoozYUyhwNqMQ5L/S2te6dhC8zjbApfMPI5OYDfWfkorRjhbmeAf4itvZZ7Jn7CRU5oxiSXcAYnReT7n6Mcm/3WAEEHRJU91YZ83YmgC+XBk0OyXFqAooMQEdVswuv4zxxheHfCjrjA+sBklqUZXYr7yGCudZedQM6GxcVnsh3CM2GoOPpxj/2gZhOx+EnquzK/1wb7op+k/AMxF7zOOZmqtwo0Tubv7wGrRBuIBPI9vdxItcsqmFvryIGjeEIuOIlY1pDxwNrxeaIX4CXiM7PSbMSvOnxQW7LF5Bbt1RIZSbSfn9JVptpGxt1kfKZoaQW3uvqOn9kP7hGxEF980A4RTb0besxA34h3AGW6zF+DFPxPDy7TNvLPOHjoefQ1AweLIhPwmoJ/UXVWj3pc2GuHa1xK5bzV4U6DqU26J+WLRA1jvhZ2LuZ+KrbMiKU7RZwBKanmiTSL8wjLiyErgUUDeL6+hVQFDy8Bx9E560Y4pZfAdHeZTKsCFYk76jH7XXTFRvnOCH7gUtO+4diOJTk8BeE27TajKl3LOG9FkbhYITbrQOXa2nKOtIn+6GkZc84z6WlG
  template:
    metadata:
      name: nextcloud-talk-recording
      namespace: nextcloud
