apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: suitecrm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/antblu/antalos.git
    targetRevision: main
    path: apps/suitecrm
    plugin:
      name: yaml-envsubst
  destination:
    server: https://kubernetes.default.svc
    namespace: suitecrm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
