apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: suitecrm-db-root
  namespace: suitecrm
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
spec:
  encryptedData:
    root-password: AgAGrt3E1HwgydxVjYzgZBP64fmaGccm8xefWs//p1NPrRj5Id6nZo4s30VjnZE3mfrorLwPlJVeI1Fkyh2ozljR4Pe4dQjHWD7xsNAWogBZkiQcji3V5JulWNaaaoMzEaYq/Iazp2mKn+SYcvxLDwXsEU4y10dVZEQf5NPu7hXsgkkNfvvYjB20HMXCHE2hY05dnFRUcK2qeKqDpsKsRmlTSEa1zL/d9SU+mOk2Zi7gmHyY9TL5hk3YaoPqY88nVpQEwdJcK+6vke1t9FHIinc3TKVkvr9OvwnuCv+zyFKLmhtlgc5b1pXsYhJQrAgCtg7MtPIrUE5ta4ckdgVba3gV4ocFZVbKOcR53QvXp9SwltULnQ+AfdTUyvYEzrnekIs+Al/i47OLl70y0yNX6E9/kE87PR9fyNIw/+cNH/cVE89w1cU+bGRxrkJEIj/iGauepobpjkrRZ+SxHgtmtLzv6+qW88Zbqfk9MrO6s/yDO1gBZrkSvECtT/P/FIJIa/ODrAEMb1gY45uvtAmdRTKn2sUuO3/CBLE/rMRGEUWrANrUAne0V5BEFm2dQlqWXIXa7HuYkOhGJptVNap7ftdzrgDN1R9rR2HordFgixTDPNf/5VItRfTX0vGmiHMY2hE/RO8xkyG9wUC5crsjW0oe1RjFThRxCGB0ZswgnaZ35U4tBPj2QXyFf3SPoYsq7+eYFoDDAYqN+OU+iN42orKKVSN1gG+DTFAWL2rsM9z01TIKSnKCXPs3N5W2oMC1KDV30nNdM6sKTPZd9T/a8QKJ
  template:
    metadata:
      name: suitecrm-db-root
      namespace: suitecrm
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: suitecrm-db-user
  namespace: suitecrm
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
spec:
  encryptedData:
    password: AgAdmHKra2X/UXmE9ON5CdnXpdvvwjhPDO5k1kGwGbfiU8gWSbQDQ9BIktijR7DtivQG4zhIQNsmo2aBO74X05CPqyHEDI/Wg2ATI0Pi/Pl7IOXP+6wEN5ApeLc/uM0OfwuI5QLHxMSNP41Ck505G+yS1Sitw4t1O5iu92FbeGQ0u6oDFFSzrU8LB0AVmbNfYiJh+LNQe5++dJiR4L7D78cijOGc4BhvodxnpWap1tBi57P3+H6QyfrYVOCZ57eyorHonhiO1u4lMuUupInYsgYfeDnUQ6Dv8KGUKqLdE1mgq0V0lbiFt5Ch25PV5FVPG5a8zCCFRdBL2sxj5M/JsHXHCFA8jQvn1iFQ0LQMLEFfck2AG1MfNBeBghwFIpG3WBaSZta2E09FdpBF4A3NvsEA4k2N6KHrgB5eD67POrNJFP5Hej14kk/0q+WQlBzOlqNL3N7T82aTM2l3h9ZeiS3nLv7r0aPlNoBGZ8hnxtzi/bT7+lSYpdge7jXvbP/BJR4Aq9rNCApyefln/Bd7kamgKRes3VYEgrP3dEbWpbp9Iezu62Ut9XLmrnjhZsQBUb9xo2ACd0Gzirs3TqBSsiH94Yg9lMYFPowe3ieQj+YUkSatA1/czqJW27nX+hAYx+Ecxtg6y1dMPWq0NqpxbR/M2IzId/NcTawOvFJiCiRLTTjlWdzJ+7vy4uBI5ai7pO9MdnfVvTPftnK95I8oit8x+sDBZkChEIX19TEYcWp3NTxo6e835RiD9JqGWbVBej38CEts6ARTHMT7pnBAQSSS
  template:
    metadata:
      name: suitecrm-db-user
      namespace: suitecrm
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: suitecrm-app
  namespace: suitecrm
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
spec:
  encryptedData:
    admin-password: AgCfKebnqv3V6YFp7EZglQhZcTVC3Jv5nxSNmNtYx5IA/kLIGMu0/nh5F+eg74yRj5n+zg9E+5vY9SUZWL52XubUh6pmq6eRHO3Q6u6gNI9vVEmMjQBJM0B9oJ5PLhMiYBl1y7ZIOm2L+XhLUzGoNLJwjb2dXUw2Z8KX3siq+5ldwv8UxJ2bpkr/dvi+Bh02nUEHDT8hnd9g2KJf6v2wIngbCvZpOaaQs2ZdUEvsfd8Fays3uuzgYsqiuftX+qLPPEIurNut79oRTeJK0CKze2hBs5Y5VZsAV4vcGssNuzEFz6xoeUf0O+LVW3CvD4W7CouHJrc745jxKFW6lIr5I1BU3kxSov7Cq/lru29JiTqZkbjl+AmuBFmU5iw4yuLomsqB46IPGLWcbdKN9UK5va3JTU2qPZhD2n3Q/wVrmIYG6m7mOHdYejcqW6lig99PkrLhXzLqVbuBfdSiYErVb69tzUU9O99xJo572CyHbBQ5ZQx7Ll3r2pVogBDpTIOh5koQLrwvu9aVE4G+O8K5yIoeT9Fyoohrx7TIxb2PaPDZWKmla+ed9BlTOqV/Cc+cOTrzzjF5+Q4RFPPSWJRaVQtWoxX90skw/eGoLPS8qO2yb9ZV36QYSUJ4jVMHBNdJCDjlu1NbM2Zj5o3qBpF0bMcekcbap75rM7Ks+7d2rP4WmWRhJK29L+xJ0cS8AMoVIt0PbLCRX8+z9W9AvdMiUK7rjJ5FAR9zTO5lKq1jY1n+uzeW+enXdoii
  template:
    metadata:
      name: suitecrm-app
      namespace: suitecrm
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: suitecrm-s3
  namespace: suitecrm
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
spec:
  encryptedData:
    access-key-id: AgBrnS8WRTd1Vgrq+8tQ9opOXXS707SfEXCVcaxq/5DWO4ekrztpY366bYvaqaWcs4u2wjOr+uIJ6XD8ljf6cWVTmZCAFMdx/nwuQd3/c+L98PTvQEeLd/swiHFH+L17iqbIyscB983ngLb59fUVhqrRUmU9IwQP2sj/T98eR2l7VklCwLxJ1IjYf8Qsgc/PhmCJ04/PACblcvK7rh+SZT3dBz2f1fxpAaqogzzVESLwxtVvqv2mpLx4i7WwZmogqHHTyyX7TXsbir9hVXpMPg0AJa4yhAuhUhzYGSBvQOQ8uQVjazD/wSSkW1cNZGm+NQxrV7tfdL1ytcCveaY2ruVRvyVOuGzrR8CZMg+Axu1J0AYK5NVcJSI/bAnl8RVDXyY9P2qHhTA1bVy+ifPcOk+K12e0zICmbv6B3OzoPpEVQolWrmCYYEFxoKb7ZClTOxxLSaR7NsVkxMX4Hg//MLDaw4hP2PuXZHzpF1fnTKUsRfTMPRdyrO1MEcaC5cbi+hRzl3AvldazUgKVZVcBKnXjGnv5n8tyTf9Y+aJ8BI2zXR7GpEVZTilLNher9ILBieNOiOxaLAgl6Jtcl0WnzzxOKwdiTUloKZMPsldZYh/nl4AGG1a2MiIwyJjzaa+sgF9LHqBsL7unTdmZOHONDZQU4gqm1EgOfLVtXTzmSfiM/J+FL5kVg8wHjMbnEVdj4pelY1Mjd7vsxnuMYBcooTPBeW2bNP75+DRDjw==
    secret-access-key: AgAUZAHI2PMyGkEPw8qjICilxZdhfhiHs/LJlRZVIi0Gy7QVtkBYwqcPRr87+o1RmZcpo9IQ4sf/sJapN1Zb4oC/9zxOZScA7Tck8E0UCyfDeg66g9IYhM+5ZQk5cJPCN53AXGFYha2PgdrTMMyyHJmZjItgUIrw/WEY/51GXuhR9eV/WDg4Yi2CXidx7vtr9uueIv9/bkPXodTAZeFlWqUOzFjyQ8/z2HPRE9cNsuFFsK5aILtWRswjSBeITeGUfW+Nl4wMbiV1HvHvQMrWVl2GPrOhOX6t8kCR5VcPxCGTUdf8wmsloAAOKnUwSRUzHk+47rwQhMzv0SufzxuyuRcDOo46JaN05hkRAHGjta0eCzbBzF/7/kn+qTfXJb900EjfC/bKxERyuef3FeqdREgHLZkE4K+Bkkda8pEZRZRUL0CQFGVSPVBxnTIa/7a0Ag1FbqxmIoUVVbfIum8S9y5ZSygPNCmm1fs+OhbewdFDlOqQ0y+QaWbw9LYMKbLK9PdezCjnjkJPhJOZ8UxFY+zaiBA8cCXelY4V0oOBWPfUhjSlVNil5otgjsHPO+h2+7Z/C1b8iU/hbzHny82mGdezFMV49IXGO1VYcNMVhVTe/xrU97zvUke9pPwRh/jTepYTLgYplnvTZ/A8srfJnB28oHY1Exk2woss3XZxf1JFjq7rtJDzQqLdnxeANbWNdM7x1KtpP9UPlY6SR4vNJdAlaLtNZyymzo0tR5MYp668MUI7JFgcOkrZjuHgW+sH1Q4PdCjT/CfvdVZN/wghTXI9
  template:
    metadata:
      name: suitecrm-s3
      namespace: suitecrm
