apiVersion: v1
kind: PersistentVolume
metadata:
  name: suitecrm-data
spec:
  capacity:
    storage: ${SUITECRM_DATA_STORAGE_SIZE}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    name: suitecrm-data
    namespace: suitecrm
  mountOptions:
    - nfsvers=3
    - hard
    - nolock
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: suitecrm-data
    volumeAttributes:
      server: ${NFS_SERVER}
      share: ${SUITECRM_NFS_SHARE}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: suitecrm-data
  namespace: suitecrm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: suitecrm-data
  resources:
    requests:
      storage: ${SUITECRM_DATA_STORAGE_SIZE}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: galera-suitecrm-db-0
  namespace: suitecrm
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-local
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: galera-suitecrm-db-1
  namespace: suitecrm
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-local
  resources:
    requests:
      storage: 100Mi
