debian_rtx_hostname: debian-rtx
debian_rtx_ip: 10.30.0.26
debian_rtx_timezone: America/Denver

rtx_compose_root: /opt/compose
rtx_model_root: /srv/llama-models
nvidia_container_toolkit_version: 1.19.1-1

llama_cpp_image: ghcr.io/ggml-org/llama.cpp:server-cuda-b10884@sha256:5ebb7a55e3d38e5fe185346fcd908033e69c035ad49b33df0066eb7cf4f7b06b
llama_cpp_port: "8080"

speaches_image: ghcr.io/speaches-ai/speaches:0.9.0-rc.3-cuda-12.6.3@sha256:5c6206a349e90b9a6782342917e72f84fc7cb60e8afd540f6aa625831ac1fd0f
speaches_port: "8000"

rtx_host_packages:
  - ca-certificates
  - curl
  - docker-buildx-plugin
  - docker-ce
  - docker-ce-cli
  - docker-compose-plugin
  - gnupg
  - linux-headers-amd64
  - linux-image-amd64
  - nvidia-driver
  - nvidia-smi
  - pciutils
  - python3
  - qemu-guest-agent
