name: speaches

services:
  speaches:
    image: ${SPEACHES_IMAGE}
    container_name: speaches
    restart: unless-stopped
    environment:
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      NVIDIA_VISIBLE_DEVICES: "0"
    ports:
      - "${DEBIAN_RTX_IP}:${SPEACHES_PORT}:8000/tcp"
    volumes:
      - type: volume
        source: huggingface-hub-cache
        target: /home/ubuntu/.cache/huggingface/hub
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids:
                - "0"
              capabilities:
                - gpu
    healthcheck:
      test:
        - CMD
        - curl
        - --fail
        - http://0.0.0.0:8000/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    security_opt:
      - no-new-privileges:true

volumes:
  huggingface-hub-cache:
