server:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - argocd.antblu.net
    tls:
      - hosts:
          - argocd.antblu.net
        secretName: argocd-tls

configs:
  params:
    server.insecure: true