apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-operator-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  source:
    repoURL: https://mariadb-operator.github.io/mariadb-operator
    chart: mariadb-operator-crds
    targetRevision: ${MARIADB_OPERATOR_CHART_VERSION}
  destination:
    server: https://kubernetes.default.svc
    namespace: mariadb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
spec:
  project: default
  source:
    repoURL: https://mariadb-operator.github.io/mariadb-operator
    chart: mariadb-operator
    targetRevision: ${MARIADB_OPERATOR_CHART_VERSION}
    helm:
      releaseName: mariadb-operator
      valuesObject:
        fullnameOverride: mariadb-operator
        ha:
          enabled: true
          replicas: 2
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: 0
            maxUnavailable: 1
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: mariadb-operator
                    app.kubernetes.io/instance: mariadb-operator
                topologyKey: kubernetes.io/hostname
        pdb:
          enabled: true
          maxUnavailable: 1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        webhook:
          ha:
            enabled: true
            replicas: 2
          strategy:
            type: RollingUpdate
            rollingUpdate:
              maxSurge: 0
              maxUnavailable: 1
          cert:
            certManager:
              enabled: true
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app.kubernetes.io/name: mariadb-operator-webhook
                      app.kubernetes.io/instance: mariadb-operator
                  topologyKey: kubernetes.io/hostname
          pdb:
            enabled: true
            maxUnavailable: 1
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
        certController:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: mariadb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
