apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: mariadb-operator
  namespace: mariadb-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mariadb-operator
      app.kubernetes.io/instance: mariadb-operator
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
