apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://helm.traefik.io/traefik'
    chart: traefik
    targetRevision: 41.3.0 # Use the latest stable chart version
    helm:
      valuesObject:
        deployment:
          replicas: 2
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: traefik
        podDisruptionBudget:
          enabled: true
          minAvailable: 1
        service:
          type: LoadBalancer
          annotations:
            # Pinned IP address
            metallb.io/loadBalancerIP: 10.30.0.200
        ingressClass:
          enabled: true
          isDefaultClass: true
        ingressRoute:
          dashboard:
            enabled: true
            matchRule: Host(`traefik.antblu.net`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
            entryPoints:
              - websecure
            tls:
              secretName: traefik-dashboard-tls
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true