apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://helm.traefik.io/traefik'
    chart: traefik
    targetRevision: ${TRAEFIK_CHART_VERSION} # Use the latest stable chart version
    helm:
      valuesObject:
        deployment:
          replicas: 2
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: traefik
        updateStrategy:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: 0
            maxUnavailable: 1
        podDisruptionBudget:
          enabled: true
          minAvailable: 1
        service:
          type: LoadBalancer
          annotations:
            # Pinned IP address
            metallb.io/loadBalancerIPs: ${INGRESS_LOAD_BALANCER_IP}
            metallb.io/allow-shared-ip: antblu-net
        ports:
          web:
            expose:
              default: false
        ingressClass:
          enabled: true
          isDefaultClass: true
        ingressRoute:
          dashboard:
            enabled: true
            matchRule: Host(`${TRAEFIK_HOST}`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
            entryPoints:
              - websecure
            tls:
              secretName: traefik-dashboard-tls
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/antblu/antalos.git
    targetRevision: main
    path: apps/traefik
    plugin:
      name: yaml-envsubst
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
