apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-bouncer-key
  namespace: traefik
spec:
  encryptedData:
    bouncerKey: AgByMFuSOqTe1vOOixgpXLY2PDsxXEytK1LLbh6SIjA383tq6wBJMvXNeUs1NPQWXPPnVVdcZkz1HQVcSZLju+RZPYEVAyxTNPiYJx9bwoLUL8iM9BXQvlt4nQKZnkMSFOAk6tesMdl8KVHpdNSvR4hIJDtqeHeslL0sCDhAmL0z+N6rcwu6tYR9U34Ur1A3kjYuw00+8dZcZYeAShqtR4sE3dXoNbynL3NLg5Trr7t3y0fPd2AZMJUPXKVd85a3ZLUyStinIJ6HHhai7+KTQn9rk3rSZnXoZKQ0rrOjd3Y46GtNN2G4UHGd26BI3eCI92sPZvHJLBFL62JuXfFJRzOtAyGS1jBvpk8F/0SzWGKYFZBiDrctFB2FGt5hGgnuDjRFUc8gv3F1Ooe3mbjoXczt99PUKExs1AA4OCwB/Ts1wJcU/QBTyPsQZOXJZHg645XrPFWKkATTTZutgo28x/e5V/6mizIPg7drU4xiV7Hg8LFIpHEdh4ehwClN6983mhVEnrn4ls+NwKyyoi5lBW/FF4CokbP1ltLEbZRXxiGLGaSKGQVe1RKThlOgCfJzf8kxCxxrqowRn56vGo/5kWDvKs46cVUvzXJih/Jhfih5DlRetahMiT2r9VnWtZfVzOR4/rNLNuck+skMtUJj39TQ1hPjROPbul3GvqA4QPZgEEqHCqSWgAxgWIWSdV4VP3xXzoK90hS4QDjRLl5z/XbASOBzN0FoIAy+tJB6/Td/IHXIAyeh2dujvDHSmf1N4sd+Nd2toBkRwr3Zzl9pJk++
  template:
    metadata:
      name: crowdsec-bouncer-key
      namespace: traefik
    type: Opaque
