apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: traefik
  namespace: traefik
spec:
  selector:
    matchLabels:
      metrics.antblu.net/scrape: traefik
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
