---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik-oidc-auth
  namespace: traefik
spec:
  encryptedData:
    pluginSecret: AgDvTQVTsglXo+5Z6VZSwUY+f4g9YwBXcgjaKm+jS3ae5BrLlaPj4mJN/68FgZA7ALB8IXl8LKzfmQ0+r+V6gLuVYeXC3KtkxHAKP8b2/EJcD73aTAIdLjXz1Tru3oshTDt63/jA39gDnmt4CM5TN/obkr0YmCI9bG3R/M6I65gkddyIKlaOjFSKPvVY30Rm66VZMwBClaFxfqXyXSA2Yfe+MMFbYhuhzAszUuIvU4gNGCpNprqwWsnDMxVTSYixkOI+ONlwY0lsRzvOjUgaZCAQ1ztLtR54YA0nfzgYh2X0Mp+iAlvMz4VmHckcfIlwXv0UJM8DIDPm8DGBJRQoR9nAcZQG7ZrDm+34Yo6wbGVEeIX55O+RDHtMf3guka24htX7JvDFgiX7Cli3+fjJ1It6mmvdkquSRXT7tWW7LV/WsJjKz7hwWeOAWlWOSjSFJaIK0c01ORPJbAWEWjlXcDq6tOrC/ShPpK60SaeUdp1QUc+z0+pEzUiiMrJw36U0yDOR3iKshBsbUh2HmF5zuLS2eG9+nCOflKeAVz9AcYt1FgJNsh4SuulRhzrKe177E5k4xHyWg/5oA0gUwj3Qu1vpw0yr2OY7rbPsHuHvisnlMDDMXdyvsHMtKEFxLfbE+x4UPaR4HxpO4Fuw4G9Hk7757CY+lpwZwVu0Ko31F8is/SZzJnEjYGrVeyx85tANlqj9lwIWO3nfz4xSCUXy/wNGfwk4qo/Oo8L+dTh2g2BDWw==
  template:
    metadata:
      name: traefik-oidc-auth
      namespace: traefik
