apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-tls
  namespace: gitlab
spec:
  secretName: gitlab-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - ${GITLAB_HOST}
  - ${GITLAB_REGISTRY_HOST}
  - ${GITLAB_KAS_HOST}
