apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitlab-db
  namespace: gitlab
  annotations:
    argocd.argoproj.io/sync-wave: '-3'
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:${POSTGRES_IMAGE_TAG}
  enableSuperuserAccess: false
  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: required
    topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - ${TALOS_WORKER_LEFT}
            - ${TALOS_WORKER_RIGHT}
  postgresql:
    synchronous:
      method: any
      number: 1
      dataDurability: preferred
  storage:
    storageClass: openebs-local
    size: ${GITLAB_DATABASE_STORAGE_SIZE}
  bootstrap:
    initdb:
      database: gitlabhq_production
      owner: gitlab
      secret:
        name: gitlab-db-app
      postInitApplicationSQL:
      - CREATE EXTENSION IF NOT EXISTS amcheck;
      - CREATE EXTENSION IF NOT EXISTS pg_trgm;
      - CREATE EXTENSION IF NOT EXISTS btree_gist;
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: '2'
      memory: 2Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitlab-praefect-db
  namespace: gitlab
  annotations:
    argocd.argoproj.io/sync-wave: '-3'
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:${POSTGRES_IMAGE_TAG}
  enableSuperuserAccess: false
  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: required
    topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - ${TALOS_WORKER_LEFT}
            - ${TALOS_WORKER_RIGHT}
  postgresql:
    synchronous:
      method: any
      number: 1
      dataDurability: preferred
  storage:
    storageClass: openebs-local
    size: ${GITLAB_PRAEFECT_DATABASE_STORAGE_SIZE}
  bootstrap:
    initdb:
      database: praefect
      owner: praefect
      secret:
        name: gitlab-praefect-db-app
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: '2'
      memory: 2Gi
