apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: metrics-server
      app.kubernetes.io/instance: metrics-server
  podMetricsEndpoints:
    - port: https
      scheme: https
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
