kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: rustdesk-identity
  namespace: rustdesk
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  template:
    metadata:
      name: rustdesk-identity
      namespace: rustdesk
    type: Opaque
  encryptedData:
    id_ed25519: AgCKe/99LPD95L9q3Lf+i0i7jCugElRjG3Baj/3jtHKPOMbGT9pBXIjNblAq5yQZQirHCuHsgyB2dedigM8Ps/mM+zY1U6BENY02NV4vBRjtLKgSK1EiOv2VbVq7fIEpPfj03fuafJ09R/xnetOj3qIW6HY5qDWqlf2OSKAaDuYYIs/7KLJJmNtgAfl+5JLLtUzJPAt9FjhpzPBaNfRoSHUD9BqqDn4jVPJNVCBOPvBBuJkf1/QUlj7H02X+t96nQ2Z+DzO+EPrPvKGBwXEwwhqpb4yiXJ105AiHsocMO050mHXCI+H8t6iql2JiBWa7NQMWdP988+OQ6Qb6Qzc5YcC3xu3i5afiq7jHcz35A71im+MJTlufKH1t4eqbyu/9u24EVBklegVZWTDGNJbEZlogkvWmgKl0hLRuz1CyLN9dFuUlGzDs+yMFD5WwQ5GIhWlhvtpUTapwTIowFVlEprEGF3hZ5nE582Y4dbyyvCN0gqMJmieJUmuag0azW19yxWjirrjaoNZP7GV/+uHlc+oCrLTUmJxhUpq6BZix7Nqt6HsGgR3DkW/eteEdDNRx6EMFghZuc27gN/R3oX8v1bLulB50a3+MImJvGOQI9e7BtWce9+mPH9GVK5aC8otpGR2n6Xx06tEFUPrZLO0k4Ce9Cj/S99TmbgqN8eKHHsO0SBJTmYJbKJff6sADaE8g9ZShzYsz4vdrzWIBZ2jpy4JHKJzDTUklYsvnyAmpE96VqsI3EbEjhZEhvIdJPtv+rCQCsxbTSTGnhPQdo29JOauZE3y66SZ0eBzmc5kAIw/usL3Ew6B0x74n
    id_ed25519.pub: AgBHy6XYBm4I9c4etLA//AzPJl1AEzNTVqPPpJJyJInJnh5iW3nd5MMTuBWHZztm/yd9AH5MFEkyYyNu9PNwtu89Ao6+Gq5MHuh/6cbkgWTpKwrkPXK/2fVdZlKi3HcvrUj8ZVp/YH95PZbnn2kiANOQJpwPaZlhhUi9FtYvJQl/gyKON76PVu02b+LhtCeeUrKqcKqo2BCEBs53JCrOc5yTf+rKsADnM25XeJDUq0cS46grJilP3he4zZvXnYNfv/SBUT+qWXbCY1dTQ+7hyypXqygefJXNYpdh8sA3gUlwBOU12e1LHIZcUVevZrO98bDRFULFcGEl/ZN+bqqlEKtpLbsSLpJmTJmSqIiqXXcVuVldUg5csO+/p2ncWbOzkSNPB+WEGAeh60pWk2agTtlhpPLL+IlCFlLH4FCYRTJ/M9tnVqzi4alZWzyPPKxZ6RmWKFNYjBmuDSIaAGwXyO1FeuQaYg1UgXyTU5edC8eYNu0YYk1nuaBQCIkqkoSj8UFA2WBEY0155SbHBw+TU4iVlZopwEF2EMEP0YtQNxL73TyBWLs4biWiWqrmBqzX0cjSlh2NblnWBiFvqFGumeRS9TixOK0fnKZU/N8Htpk8rgTGAPRguY+oqeET5NAtZJ91Bp977zcTBcfvfk1s85AH/v+up6QGulABAH7b1bzbgbeHqiokQPXAPFxcmT31U46iNxN+Dm2JiG5m6CO8Gx51wNvnC6VcwqYFQ07Kc/rV8ivBeytF9G/synJfhA==
