debian_left_hostname: debian-left
debian_left_ip: 10.30.0.27
debian_left_timezone: America/Denver

left_compose_root: /opt/compose

left_host_packages:
  - ca-certificates
  - curl
  - docker-buildx-plugin
  - docker-ce
  - docker-ce-cli
  - docker-compose-plugin
  - gnupg
  - python3
  - qemu-guest-agent
