---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-oidc
  namespace: forgejo
spec:
  encryptedData:
    client-secret: AgBbDjRRC/abTW22rdYX17yP7oz0dDyls8xPUH4Z9Pzu7thYmD80rcYbsCAquFwk+spyj8TvG28iaU2rM0hdLjOV3spm9Kc1MaN3MTxSkCv5TzOGdq5/ihdYhbN6ESa/DKX1PFcis5EgZlcZ3D6iDSt0GxTuX4FzQK1aDfwW816NJuVGPOqz9BZ9fmS6iXLF3g6ISYdBji3oq2/Cwa/0e14TYOFtzBSmE5JaByEuuZ+w1yePCefo5qUpW2aQDITLusFk5WLOJyx/zk34J5VAkg+re8R6wAjsjMzFTiQsQKDiTJncSfvsTgti/qouJe0oXRTf9YzKC5SdQO6zJNCBpJR5sOKg1nUfmIDTu91Lum97AiF9wkbutlNAzGempk3/5M+IBc6zC8NH5q/7UCHY6IFZRJxyA2uDu0oWtOLAg3ritEpO3lleGY/CWAkjfONLqwb9Pmoqs4RMjgC7yOo/UK+TXXkCH/2fAC75l3jIlIu46eOoyuyK36XacgzU0iqjQrILYPj3ZjxlmMdMgyF2KG+gzrjGcB/sC1wkH7lmzYbqiQlBKp/5JR9U4cTZz5SyiAvgMshN3rAz3HIjU2KJpgwsoMK7aevN40/wf2gAMKZMFLazMH2XDKie69+uQQlZQfv9AvEXPHRPkUMmWtcN8dDD6PatSv3jSsmR6nvzhvAZhp+fOibosZUFPR0nv690CRm7Gtb4kcuKrAvyp8rOEh3K89AHooIXFMt9HctJk2e9KIpuCLm1yLsmZlG0OqOlVYUWmtbZ4k7TGzoMBVrbRdypBVpUDxs9RiY4x5hQIiz+8+wte+zx425jy1X65LrHBr6pOyiD6KQByrQTLTbhVThcY+3DKhJupMYY6aVX7RoaGA==
  template:
    metadata:
      name: forgejo-oidc
      namespace: forgejo
    type: Opaque
