name: antalos-debian-left

services:
  live_transcription:
    image: ${NEXTCLOUD_LIVE_TRANSCRIPTION_IMAGE}
    container_name: live_transcription
    restart: unless-stopped
    environment:
      AA_VERSION: "3.2.0"
      APP_DISPLAY_NAME: Live Transcription in Talk
      APP_HOST: 0.0.0.0
      APP_ID: live_transcription
      APP_PERSISTENT_STORAGE: /data
      APP_PORT: ${NEXTCLOUD_LIVE_TRANSCRIPTION_PORT}
      APP_PROTOCOL: http
      APP_SECRET: ${NEXTCLOUD_LIVE_TRANSCRIPTION_APP_SECRET}
      APP_VERSION: ${NEXTCLOUD_LIVE_TRANSCRIPTION_VERSION}
      COMPUTE_DEVICE: CPU
      LT_DISABLE_INTERNAL_VOSK: "false"
      LT_HPB_URL: ${NEXTCLOUD_TALK_HPB_URL}
      LT_INTERNAL_SECRET: ${NEXTCLOUD_TALK_INTERNAL_SECRET}
      LT_MAX_WORKERS: ${NEXTCLOUD_LIVE_TRANSCRIPTION_WORKERS}
      LT_VOSK_SERVER_URL: ws://127.0.0.1:2702
      NEXTCLOUD_URL: ${NEXTCLOUD_URL}
      SKIP_CERT_VERIFY: "false"
    ports:
      - "${DEBIAN_LEFT_IP}:${NEXTCLOUD_LIVE_TRANSCRIPTION_PORT}:${NEXTCLOUD_LIVE_TRANSCRIPTION_PORT}/tcp"
    volumes:
      - type: volume
        source: live-transcription-data
        target: /data
    security_opt:
      - no-new-privileges:true

networks:
  default:
    name: antalos-debian-left

volumes:
  live-transcription-data:
