# ============================================================
# ArgoCD Installation (Helm) + GitOps Bootstrap
# ============================================================

# The kubeconfig is generated by the Talos/Proxmox stack in ../talostofu
# and written to ../talostofu/kubeconfig. Point the providers at it so this
# directory can talk to the cluster.

provider "kubernetes" {
  config_path = "${path.module}/../talostofu/kubeconfig"
}

provider "helm" {
  kubernetes = {
    config_path = "${path.module}/../talostofu/kubeconfig"
  }
}

provider "kubectl" {
  config_path = "${path.module}/../talostofu/kubeconfig"
}

# --- Install ArgoCD via the official Helm chart ---
resource "helm_release" "argocd" {
  name             = "argocd"
  repository       = "https://argoproj.github.io/argo-helm"
  chart            = "argo-cd"
  namespace        = "argocd"
  create_namespace = true
  version          = "10.4.0" # Update to latest stable version when possible
  values           = [file("${path.module}/argocd-values.yaml")]

  # This release only bootstraps Argo CD. Once argocd-self is running, Argo CD
  # is the steady-state owner of its chart resources and configuration.
  lifecycle {
    ignore_changes = all
  }
}

# --- Bootstrap "App of Apps" Application pointing at the apps repo ---
resource "kubectl_manifest" "argocd_bootstrap" {
  depends_on = [helm_release.argocd]
  yaml_body  = file("${path.module}/../../argocd/argocd-self.yaml")
}