server:
  ingress:
    enabled: true
    ingressClassName: traefik
    hostname: argocd.antblu.net
    tls: true
    tlsSecretName: argocd-server-tls # Hardcoded name into helm chart
configs:
  params:
    server.insecure: true