# ============================================================
# ArgoCD Installation (Helm) + GitOps Bootstrap
# ============================================================

# The kubeconfig is generated by the Talos/Proxmox stack in ../talostofu
# and written to ../talostofu/kubeconfig. Point the providers at it so this
# directory can talk to the cluster.

provider "kubernetes" {
  config_path = "${path.module}/../talostofu/kubeconfig"
}

provider "helm" {
  kubernetes = {
    config_path = "${path.module}/../talostofu/kubeconfig"
  }
}

provider "kubectl" {
  config_path = "${path.module}/../talostofu/kubeconfig"
}

# The Sealed Secrets private key must exist before Argo CD creates any
# SealedSecret resources. Keeping this namespace in Terraform lets the key be
# restored before the app-of-apps bootstrap starts.
resource "kubernetes_namespace_v1" "sealed_secrets" {
  metadata {
    name = "sealed-secrets"
  }

  lifecycle {
    prevent_destroy = true
  }
}

# kubectl is deliberately used instead of a Terraform Secret resource so the
# private key is never copied into Terraform state. triggers_replace forces the
# restore on every apply, including applies where no infrastructure changed.
resource "terraform_data" "sealed_secrets_key_restore" {
  triggers_replace = timestamp()

  lifecycle {
    precondition {
      condition     = fileexists("${path.module}/../../../sealed-secrets-priv-key.yaml")
      error_message = "Missing sealed-secrets-priv-key.yaml at the repository root; refusing to bootstrap workloads with an ephemeral encryption key."
    }
  }

  provisioner "local-exec" {
    working_dir = path.module
    command     = "/home/linuxbrew/.linuxbrew/bin/kubectl --kubeconfig ../talostofu/kubeconfig apply -f ../../../sealed-secrets-priv-key.yaml"
  }

  depends_on = [kubernetes_namespace_v1.sealed_secrets]
}

# --- Install ArgoCD via the official Helm chart ---
resource "helm_release" "argocd" {
  name             = "argocd"
  repository       = "https://argoproj.github.io/argo-helm"
  chart            = "argo-cd"
  namespace        = "argocd"
  create_namespace = true
  version          = "10.4.0" # Update to latest stable version when possible
  values           = [file("${path.module}/argocd-values.yaml")]

  # This release only bootstraps Argo CD. Once argocd-self is running, Argo CD
  # is the steady-state owner of its chart resources and configuration.
  lifecycle {
    ignore_changes = all
  }
}

# --- Bootstrap "App of Apps" Application pointing at the apps repo ---
resource "kubectl_manifest" "argocd_bootstrap" {
  depends_on = [
    helm_release.argocd,
    terraform_data.sealed_secrets_key_restore,
  ]
  yaml_body = file("${path.module}/../../argocd/argocd-self.yaml")
}

# The controller is installed asynchronously by the app-of-apps. Wait for it,
# reapply the key in case Argo reconciled concurrently, then restart so every
# private key is loaded. This also runs on every apply.
resource "terraform_data" "sealed_secrets_controller_restart" {
  triggers_replace = timestamp()

  provisioner "local-exec" {
    working_dir = path.module
    command     = <<-EOT
      set -eu
      /home/linuxbrew/.linuxbrew/bin/kubectl --kubeconfig ../talostofu/kubeconfig -n sealed-secrets rollout status deployment/sealed-secrets-controller --timeout=10m
      /home/linuxbrew/.linuxbrew/bin/kubectl --kubeconfig ../talostofu/kubeconfig apply -f ../../../sealed-secrets-priv-key.yaml
      /home/linuxbrew/.linuxbrew/bin/kubectl --kubeconfig ../talostofu/kubeconfig -n sealed-secrets rollout restart deployment sealed-secrets-controller
      /home/linuxbrew/.linuxbrew/bin/kubectl --kubeconfig ../talostofu/kubeconfig -n sealed-secrets rollout status deployment/sealed-secrets-controller --timeout=10m
    EOT
  }

  depends_on = [kubectl_manifest.argocd_bootstrap]
}
