apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zammad-db-app
  namespace: zammad
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgByhdvs5Ei2bFU178lFUr+wsNkT9V2FEKyVCdOv1ahC6wZw5zcZ36Io+bLuBMRsWuJNOQBlM4yNBjfKNfDa9FwA70HkBGCWpC5Bz8dYmfg4AU+3bywAf1tgksZyTkWOIdRXOJfBir6uSsqSXRNsutkH7dQ56jHLhFK7IuMEBnIfnnK1SfsWTtNquWcmznHMs6o5QtngpIQCN3vCxwvA7d94SvIK+cCc3jNSdc3DWnXVixiUQhETn/QFiGJj0KNXAV96HrV46JmPT0WSZyZVLDqJeRcxiAl+SCKZGy0KLNlG3ce1dQzfUkNPKDgO2qUbw5KZti5CHIZ8DAPmQKSidVh7OpvFR9eFLXXCFq1fax9qLxNKA9pX4forD1FpIhb3FQFHX8u7ZzuxkdcnLriuYAxsURWa2ftHHktefTI6yV7i5xmtzO4mUhbM+aGYGkLiCiLjgLEwvsq7UxqeUPmtKZuLHeVEozYiO2Wzsodul6kXzxPC6uPiWM3pGalhAhGgIS3MRENvEZHdCQAclw2dTFr20uyqMehujJroVTJ4oUpo75I8LPY3Z0yermWHJBhSaWedrCfMo8HJrUg0d2V2PAtOqQrrBhPxFj+boJBiEeALbFgmhHcv4fRK2Xn2hDIzE2f8a+VQStuhLN0Rsx30Wf1PDc2ryV4HSJAp0NpilBc9oJ9TM9qEshriuwgFWAJN0bcieEE4zctu4oIXxWiWZhivykuEqqDFY8/lu3Gou1WydFq/ypGg7Wxxo3KUIjtbpibwyu9nG0vz3kYdXpRjzfaE
    username: AgB/44AosySVUNpNNLJEzav7Xobww1QrQJpBNkJm5xjWOWbEbXWg4Eh6OwhG/BhNEEiee5RVl8sa0epGMJZpGvdJIwiGgeZRGvSWP/hmYWeNdm0ciLTSke+xifbLQeems8K8J/pCiulZBJ4SsyQXzxypmnyU9l/tO1DM59Tm80KbqI3XK0r12z/4mREQguUjHxRp/Ti79OXa9sKW1OO3Wg6yoLw+Fg00lcS29yLOFHNokxa8/RzesfClP1EyPfFfCs90A4Gsc8qA/H2oC7sSrERywLDNb61cur/5WPYxxAInhu9XhTIVRBgx6vobLIJcEfiWklBZZgyCcFcpX5lZ/pGannMZwve9egehIjkxzIxAEbi7KgDYUBE8ptkFJkpg6g9jJoFiZFmHjvjmEpXEuyT1XmS+4VRFUGNxdcQjmFiwBoQsAeRKDgH43PVwn24FLztUpIdEp0GHLk2tFLq+IFWRdKw6DR4yzgVgMwDxLZ2sub5v17p7vf2/XfTA6rA9IE7nZrmubVxJMLYRkwpzOOyZx284ATBNh70wceiIe+lXYbcnAV4+Vb3ww8tqPU5ub9SVVVSG7M+4Tv4mPzSklGAP4DkS4UcoqgjAPva2Pur/OUn4IeC3itJNmk2oh5jcc9b4aKoKIID5q968EXWb8x7CucpM3ovhXtr5vZj9HuASzxpSHJ+Zw9hTjWGmuVWYj/KIWkofN1A=
  template:
    metadata:
      name: zammad-db-app
      namespace: zammad
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
    type: kubernetes.io/basic-auth
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zammad-redis
  namespace: zammad
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgAgVO/aH06nwH5cC+tRWyrYFO7BaM9tR5Oy3487u0J7ZsdmisKDSC9FpJ2RU326eESvZ4bCmRUyy15NzP3aGiRebIRzhpVXfI7EI7t2DoTyr93MfuYlDTKVQNaV8ixO+GL5+5PfYcNXZDscRgrOIsPWceXW34OqFTzK7hYnXp1+DC2BGN44mO2UQDKW1d4OXSI9E4PL4e9HqJAOZA9mKZ0Qvvzlv9bcu35epSlUIqsS7/khG6KL+lfXTPatW3c8gDfiVb4UKjaOdNs4m6D8aiF6iwuhCIuRIm+aDlhZhXRCLAdMUT8ovDhR9h7dcVUx/m/CwI5ENLEMfzDttj3ElJ+jlKUw1eOxsdM6LdL5q2+0JM640x7Vv8mH8kgeC4MfZWJNGURzmOTw2p+cGTHfNqbtfBfAfdWIo9T9G3Q3g+E6PFBN1ySQF5TbotryYCbBOP40S2tkqDySpdoL+t93C8Th3j8nZxNBLKbZzqTa5WtZh+tgdliLm1jDl6nodW2ZYoXpMoOPBR0gQp23z3DZwNID/v0BsqiSHJ0ZpbavUZolQ/psnY7Mbb/xglKjfrAVAbRcebgigFWSgl67vp/gl20t6J3El9aB8zdaPwKt64FWHUfCVwPrsvbdpFqe527BsQN7jPREyo0rPwUzBw+aTSp0k8oCdKe+f1ncBoSU7JbAXAR9YZjwzRE4HI5ssoRD7qJ8zwfupuE6EG476/RcZ85e0XF4X6Uqw3dYdRcQisK1JCICKZnzu70oNrBMj+WBHpkywh8uipm7NrA0wUyjYnvr
  template:
    metadata:
      name: zammad-redis
      namespace: zammad
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zammad-storage
  namespace: zammad
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    s3-url: AgBOAMkGizMV/M5tePwbyRzGrL9qChoY177CQWiC8TB+LYIn/5sw8i1ZCmIPizfRe9Me5Jh9QHSgpfy7ihsKCUzaJKiJ2JoBFSwH45zXUYxkTvbBOvQBzSQxi7T0s3WP4+yTeSpbZZkTHKT4w4rsBLCfXklEaeX0782P/cAW8EYpEuRAqIguw5K46GCRMqpyMeg/gQ6SCZXXoQPunLdtWL0bXErPYAZaltnZyCC+WqrCypSDfrgaLCtXVG4iWVZFhNzBtFkhlWZTS8Zmkd52O5dtohqLUcqjx7H0md3Rk87/sOSZv313xjSZC4AAgmP7IPByNVdAkx2dL/ToCOHfdmi3U9fhZ4agkKsJW83y1tzHx8FL5uAw/LJk7Mc2mL0M3eswORPBvr5fvl/i2WQ8Yd3SGJ2uCHX+tfD6MEztTzCFVRde9Iv9e74KyDWgVB+WhoXs9ZIQmVj4nx3xkXDH17/H40QtZVvZF113BDqB19sgDVcakdWAxKkj8peWEgsp0rW2rnzRrRgUVpfZFPXJDEnLyHWBfgaE4E2EIU8/CZ7u0r8IkleoICwBk5ug9A3fpUr+ruMmPEQFn9Qgi3pCn9HzaAq01UtZcWgUFlhEYnuPrNJdGTYCjLPTXbJmJJBgvDEGxT6lnqX4L3kk65lpsojs6hzpRbOuvqMTkUXLY8xO7hYHRCRh3USYtiV8QJhrdQd1r+ObzPl02RoYeq0O7UaCy0vBoryEd+j51bc+P8OTIZFRFW13z6zFkF7bEkzEv3Of8T4cky3p9OTbpZ6CBo6nLLXvU2z5GQE+uqh3DwHlAilGEz+a4ikzEO7H57ZXAvOUwdmDMGexlinzkdDKRLIH56l2x0sXCYjpcu8h1T8feMxC9ZQniKlkh7bcDu6DYfSjfq3YTDMEMhmRDiiZ
  template:
    metadata:
      name: zammad-storage
      namespace: zammad
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
