apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: stalwart-db
  namespace: stalwart
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:${POSTGRES_IMAGE_TAG}

  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: required
    topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - ${TALOS_WORKER_RIGHT}
                  - ${TALOS_WORKER_LEFT}

  storage:
    storageClass: openebs-local
    size: ${STALWART_DATABASE_STORAGE_SIZE}

  bootstrap:
    initdb:
      database: stalwart
      owner: stalwart
