apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: stalwart-db
  namespace: stalwart
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18.6-minimal-trixie

  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: required
    topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - talos-b63-g32
                  - talos-vu1-efl

  storage:
    storageClass: openebs-local
    size: 20Gi

  bootstrap:
    initdb:
      database: stalwart
      owner: stalwart
