apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-common-env
  namespace: stalwart
data:
  cluster.name: stalwart-search
  discovery.seed_hosts: elasticsearch-headless,elasticsearch-master-headless
  cluster.initial_master_nodes: elasticsearch-0,elasticsearch-1,elasticsearch-master-0
  xpack.security.enabled: "false"
  xpack.security.enrollment.enabled: "false"
  xpack.ml.enabled: "false"
  node.store.allow_mmap: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-headless
  namespace: stalwart
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: elasticsearch
  ports:
    - name: transport
      port: 9300
      targetPort: transport
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: stalwart
spec:
  selector:
    app.kubernetes.io/name: elasticsearch
  ports:
    - name: http
      port: 9200
      targetPort: http
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: stalwart
spec:
  serviceName: elasticsearch-headless
  replicas: 2
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: elasticsearch
  template:
    metadata:
      labels:
        app.kubernetes.io/name: elasticsearch
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - ${TALOS_WORKER_RIGHT}
                      - ${TALOS_WORKER_LEFT}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: elasticsearch
              topologyKey: kubernetes.io/hostname
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_IMAGE_TAG}
          envFrom:
            - configMapRef:
                name: elasticsearch-common-env
          env:
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: node.roles
              value: master,data,ingest
            - name: ES_JAVA_OPTS
              value: -Xms1g -Xmx1g
          ports:
            - name: http
              containerPort: 9200
            - name: transport
              containerPort: 9300
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              memory: 2Gi
          readinessProbe:
            httpGet:
              path: /_cluster/health?local=true
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: openebs-local
        resources:
          requests:
            storage: 20Gi
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: elasticsearch
  namespace: stalwart
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: elasticsearch
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-master-headless
  namespace: stalwart
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: elasticsearch-master
  ports:
    - name: transport
      port: 9300
      targetPort: transport
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-master
  namespace: stalwart
spec:
  serviceName: elasticsearch-master-headless
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: elasticsearch-master
  template:
    metadata:
      labels:
        app.kubernetes.io/name: elasticsearch-master
    spec:
      nodeSelector:
        kubernetes.io/hostname: ${TALOS_WORKER_RTX}
      tolerations:
        - key: quorum
          operator: Exists
          effect: NoSchedule
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: elasticsearch-common-env
          env:
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: node.roles
              value: master
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
          ports:
            - name: transport
              containerPort: 9300
          resources:
            requests:
              cpu: 100m
              memory: 768Mi
            limits:
              cpu: 500m
              memory: 1Gi
          readinessProbe:
            tcpSocket:
              port: transport
            initialDelaySeconds: 20
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: openebs-local
        resources:
          requests:
            storage: 2Gi
