apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stalwart-storage
  namespace: stalwart
spec:
  encryptedData:
    s3-access-key: AgB5l87DO6ISKvdVcbycAKmc8bcILmuKtKC5eOD6FFcfZjdDP0VlDBAhPUIQ/g6cXoV9SgpVI+vpkPSt0Nl3XAbYkOaYUJM2cwZqS1WmtAHDQ5z/8ZNhBwJjqMrhKTjfXYK486Fb0Vc51qzikTfAzhBbwt/EddVSgl2/dxG0/TlmLh9oys2oAqAA5PXI/81Yc54D15M1vR5g3pMwBIiOJKFsGaEsqLT162HBOXiGWQlTM44nYCUzM1bTAEpP/ztKb4taGt5R6UnGSdG7wMQeBsubihw0YPcVEvz/HxLSfZXLuua4LxQhL1g/7vmJREZKtLAqX6xg+sxllXsWavk6uELLxrp5jMS6uqLv5Cr5Ibho83j9y6rh3LJLjHiNWWHty2IA7yWR+DlYL4BO0aNpMTL4yKqd42HcHPcznWW/afz0C4C341W60m3ynb00GYhmcg1D9GnYMPNFW4TJqtBWzq4Nh41jHYt0tCXeDF9uHJxHed+Vga/Tfu+4U9HlWos8/nyKWSD2e+BnW4Y+1zw3x/N/zvJROHzcUXFHY/PlinsZ9WG+DmWDAUex7UyKjVs8KFsWyZ39RQtvyOgFKyE8MoQbKRfV9QGrJuM72INw7mQkn0/hmWmu5GhBQS1oboamEPAHD+DNf1+JJXcTnTpUjmGCva36iaQLU2J/5EdYBoHLkP5iC7FV4CtG53DEC6W9UMda0aAGs73ev0v8MPmmj9CJeyv8Jxjr/YraGQ==
    s3-secret-key: AgA1cAIvhCLhlj6H/fCGgnAKYMSmwRQNTA3woTczMYO2FvFmf3TvcLavt3UJf+k32Z2zsxzTlZf1bdtz+E5z3v2ygjZYi1uEL0DEaenEwAnQtJ3hJsOGBAC//PP4NAXuX/XXvrYKr3fFB2+9a5/oFbfPyoFP1bPz/v/XlRTeqfkVpvhBbOWJnbh6HH0TINJHC5iKcoOs1pRU49fm5SUtx6cyUF5qfU/UfRw4PJeyCyNxFtz3AecDhpebV59rWByVY0ERUOI/mCh5k69avckESNZ4xtg8bOnxfWMgXFl4r3ziq07J5c16EuqPZzGm9xL8qW+EMy90/HnmKg3yxNm8DILGscvxm8hSWLBfaZ3N6SFB4VkrZU4IAefq0XmHH5vu4H90Rt+ISilORldzcAxCivAv5BJSbP/csi4kUWhOmC2PUhv8F1DyjXAH/xZlP7fN+eS7FMlRWn5U7rwHW5TlQxCvtfJMafkREIC7Pj1h0igO/cZAvqr8IcXCOz9vZejkFtMLq8/0qGb0PldPGNJLLrD9Ai5642YNqBmsSMqVFlSBQ5E7UdCk3AkMST8qL93EO5WrFW3vablC0leJQqx9a06X4neH9lNTff5ehHWm7NY8TPxyCxS9MaTZkw0HrNo/xx60osyYuiEc2Y5o7DY+APORfNdO1NepDjcWJMPa9jFxAWNAHocAJTy3k/s+XraUXEIiVCxBXjWbGfTeDPT6gMxCODxLVVdXj5Dl8CvpuNF/+ltdjLefdRTgq3OvDxG2a5ReP5/vm4r/AhfLecFe7Gg0
  template:
    metadata:
      name: stalwart-storage
      namespace: stalwart
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stalwart-redis
  namespace: stalwart
spec:
  encryptedData:
    password: AgBhwbCvsmvtPMGMYTlgXB6+UwuKIhDLsD4KL1xaL59uyTsqGWCUNAUCOk+BZirUzsu+1yQT09aXLVLNq6GBYMfJx5FcR92f8DO3BA5HhtH3GO+zV4l+RtWdqIC1qlaxanga3hj6UioTyX/2tM7ZvfhsEq+KpfZmwLIGO2MeqkUvcmxUaw4rjAkwtCA75srFphvdWq0sgqRvLCHv5i39K5FWTRqJwJimnm1ZwHEgUJxl3CbkyYi7Zido7LZThAiu4qQBll20nq9vl0aNmzsbFaq4foX8uieZccJiuosuBoGtDvMimY/1syCfFdJ0A0EdOb7rATntU/uGQ2DSuvTbw3HXXAxblR8ksu/8cR2PwzArQO4p61qxrUJdwrYgjZ/XWepxqdVp6MhyjVrH1e8IgooSlkp0sThq5yN529QI5Oy+ZnLIGhgPMp2Qtk++n0XgKlUNfFsXWNBSuGfkgaClzGC6XvViDlTlmbcXukiZUwMZH8/Md+L3KJUn2IQI7rUuKlbBaFUfAJtmmSHsZuz+f4lNwmUE0bmf/MM9WOF753ibpXnbKcjNlFGg3gp/AAkicgqXVpmLlQP/lmT3/bZMJUnbtQrZuSm4Y+cTR4DzKMW28kySggbPeK6jEbVXKrATmRiXqWDjruM0r1D5MLC6wGerQ3eXD1qjaz29tE5BnKa2nEpsTFlTegaHQPQPlGg6RUJbnlEK3+WCfkHg6IJ2BPPO41SNu4saKmKTFsqyyJ8dhvOD7eVmKTgJB3Byd/yXwHZbOD+tOfxeS6EPKb2jHTpt
  template:
    metadata:
      name: stalwart-redis
      namespace: stalwart
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stalwart-bootstrap-admin
  namespace: stalwart
spec:
  encryptedData:
    password: AgC7E9158N7YNYcm92bQkemeHLlGb6cGwi5KVGiKXsvPsf8a9FCM50d1/7QofA9gG2gXRC8dF5FzmsIHl1Sc0//A81kGfgvc7OhbtQ2keG9pejOtb1qZjH22xLduEGe42ZHU/5bAjJrE2Rx6rDLCPLxer8YQ6zqnhBjLlRYU25FE94UJk9UHJQ4u44mQLFIUW4djcaooJjrYmrg9RAhxu5IGZSiBf3prp0A0lIZhfGxVYdcuC9FHGzFgRyHkdud0oLfO2oNPPFWSqdRClHsccuThj9vqRsytx7d9DljSo31Xg8CvVvcj595xZLoCJ1SMmcYluIlRYiySfvvrb5Sbq3hvUKzJ2j4eQ4Ab82g3tj5AhrO/SKvfD4jL2e+35MADWxVkLLt1HyBY8F7xsuWWcQYlcPD971MulcMX2SsrY5IybAQrk3G9fMGLsm8jXTOJCZGmLKDeQUK7Mo/LDgGIf66Yh8c6DJNyZw98mTE2ROAcaFcAda+PkSEELaJVaVDtst1UXM1DkHu2Pg7wri8DlGpYF5G6RDnGitZgGQm+7RwhXtM0pFeMCrxTvMoIUfkJNZAVB/BUKYr/D0LU96mLxGl2hycVJzaJfB8AnXHyOoU8HQWfOAJmDiuBedhNR1wEDKlAXN5CmwouXphRqSwehRSkefwfU8CkG5PkMBVdXAGeheJxoyXff3j28W1RyC2HX1OKjBneNPbA4PF5DJhTSd0LD4QF6uskpJptghRHiNJK6KFw9UKhauUeI+7Q4zCl7KgodYBl2cDa5WmrZhmECCi7
    credential: AgBobP918DcYPQA43tGYmI8ZK5CISGP6CKfRJq1gcM1GF7hUzjx5zEEZkw5p9swI88zy1MpPUBo02cS3gS7m0+C0uNvcvb1JdvdKSj3L11WVI2eMz8qQF5D61xhW2a164Oyx96xyJ6t27S3+4zepceitH8eIXVZQkrPOoCVo0OyJAw7aK+MhP6dhKW697YhfqeNFHAmPbWiPDQwqV6H2fuc5FrkP7AHtFIjchVtgC8/zWts3ExYW5l4Wxmvi7VVWgDXoh1goTJd1hPtr7pdaMNhOddoR+K25Xn4wYpIDjnu56JwHBRp7wQo9ncHlQnOdUnePzijQW/wEWljntCT4hV/x8HT+vOxuaJgXfFOIY1OYbPSpa3cj67AFG1ShobY3owoi7wW9wLzWqQc/x5b01CaXkAPTmRFrRinGprRJPlRmCKsBbYzDcEAwpDx2AKjvinvs0wMIfmv+2lpf25qRqpB973PBEsuUcokQtmRcWl6aK4+5aqIl5vzyKIn9EU81U0RN48E2CAsZurYIIVMAZ261PmgKuLdThySVW7BCEspTL1Irz8A901Rp/2DB9OCNSsokP8kmBkE9pMYgx5NsgrttbHkPXSzwnybWqiHc6TPyAq1XJsCw5XTX+EpbS+nTgKItaryI15osxe9XC80XzXhvQvKl8d2KUurkDgdNSDV4bVzp9ZxWGBfi+PVSfn8WRCPqVArUzh7xscTAtkTXsi7Xa6o7XxitaQZwpgw28Jy0Wo5FMa7BKA03Ujh5g4FFginaPkqsy5gNJij7XZhsbu0IWnb5Xf92
  template:
    metadata:
      name: stalwart-bootstrap-admin
      namespace: stalwart
    type: Opaque
