---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stalwart-storage
  namespace: stalwart
spec:
  encryptedData:
    s3-access-key: AgB/D+WUCqvp3dPxzCVx+E55u+KIQqifFHrUgeqomTnQ9gdBCyE8kfXd670kkJLZZOBozqKGc/ElU8N2D0SFEi9WDFhZ0dM24Mv/QjdQrX+IEvTgf4jvIHxxtJPGDbWWU4MTIrfJI/yGUkKv+Eb9uh1Fc2UwcKf7txnLetVjQlawaQn9/YPWlgJY9AxgymrK90vToRMZYZwg6vCeSUeg+AZw/+pnguKVVeieNvBwai/Y0eGUoqpSuUFRzd9l6dsKHLdt/XlsrOyL+/DkCV0RfkRh77Ug4Eh+yHtF14z7b/+uI+CgaEIROeKGXjoNsvPxR00+wtdI2wGFURSp1mn+qtC+tZfxTS+kt+Abt4H/e8DeAM0Wqwsyi6f4KfqHtvcmeTK0EKmeKJEzZ4w9TtHONAwUcA4QlYbTWkhu7pHSUmbaw7dW2gghI91VL4QeHQ9sS6IGWqS/fS9gRa1ZOxvBTo+p0U6tLgh2ghMQ6mYukgZaORg+YAaI7yfmAm9DlSug8sGrhk0sdMSQI7RcmQDRl9RFRMj5mhve3sNAXrp4n/9VOLx4/2FNU89lxtXF7MJdOUE/xOVee0DyvBuGM/OPuT3hphc6dCgQuuhbsauNiezrMxMaQ0fTjNbGa/XAuU/+m79wdkzGNMzvAmbiEbIQtC0VvU2llmCSsN82ikwXP+ygR7/E5e/J/RaYbpyYkvdM49rtRrJYidMdQgQ4k6VNI+PeRlchBvWl3lOLlg==
    s3-secret-key: AgBUBii+pul4TJzBO1SVNqbP6Qz+O9QmoaB+yxOaCHRB9Nkt6KV9+pJXXuZJ0h0jOmrngpfVbDUJHrhKghHnlicWBMzcjY27O1seb7Q1I2kuweUcwaDsFQVw41dEbyRYQ23sakotkbVu4B6WYD0m1cbxSIpjYOnsmHMryAKvE2MmBSUTQlq4gUioyHU1nEuaUHcWPkPBtzh4leWv3ZKgkSjouv1qAmYJQj97wCMYEdN5J2xGZ81xlHeR4qB0QQZRXwzvSyHBgT+9ZT0edpCbi0dy4yFAa/8c9dROsGdSFRH0yux4I85PADgtpy/NViTWMK2wu0ouTXmP79V69eRLt/4t4i19X8LD3tueSZ+BEkCK6y776DNYWZHcePGt6HEvGha1/bmADHkFHABBjgSdNrKRSPWAK+jdo3w+TCQ0HcXXSGsL7thWK/Nqs7N7WIh44g+KQC7L8YdegRFM+5lRG5XxthxfBN9cVBJGSXh2yNqeqjAnbCbEHUbzOQ+4dWfAZnf9lHwefVutMkhWeEnjpVM6/SKONVLlpR0JF8RQeW/WWyaN4oXM/fJNhNQWizMxpKIzGNGtRMwD2QTMSlAy5jHjSC2GXL+h47cJ04faW5yrK4uza56Ek/TyHY2rLLmVuzyg6y60WTY/cw+kJLEffTL8kVAV0lAFveoHpn65q1TPGpfvelsB5oBLj+5TEpRDiB0AtK2hAs5VcYzU2/VyUDox1VlK90koA82afqplJSV9IEJ2Wp65vhIQBygoXfbmP7rJyO3a1yHV3TPXvzAbCVw3
  template:
    metadata:
      name: stalwart-storage
      namespace: stalwart
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stalwart-redis
  namespace: stalwart
spec:
  encryptedData:
    password: AgB+Ql8uCe0+lkXChZN9+kND63KwfpyzU23hQUj8TQtHdv1Uhc8kE6E6wY6Gb7USjwCccRT8GtEzx5SqDj1NoBly4hJLiMZJAK5k662UikyrIaewh4ceJzm1MAPFM03/phHapBvbsFfCtrXpmJv2YdD+fUjfH8HpEQ8CxWHhiREAg+tM+XGPLKB8mQvTOMNQzLR7JeBdeR3+M9EZyAH7UfA7mlXsgZUIskLMJ8BB/RkvuhoX9pTswTM0gMTenHCVoqll8N2uS+0pJn0ls7LHK6+ptr5ENHwDpvjimi+3HioNuCOATHSkFMzA9RcmbZFbdkUQJLcPXsma2/w8kLXoczgNENQoiWDT652BQy9EV1JYj65+c+oz2mt5r/izQbVb9VOAlRPyZlTwe9cEiyaZZbASrODvKNap8kRaZG+5cSgb5RUlMf9HfD4Mfp6HM/X/1mrBwJKpZAv6iQ8BuIfQdePT0nxcRvYuXoCSM1NnwU0qZuZAcZO0ZCRAX8IM7lfE8R3sx1nELe4zodXb3+kqlYaWP9UViSeUn27yFhUPE2rBODJJ5NDo0ZA8miZn2MzIYN08Ni0xfko66FUz91R12EuipcVBww01yRyjETZ5NlsEUtf6PFEcUa9Y+05boK8xFWYU2TcMEmbo1EnvGqFpkPcdYoTCa7bX61KuKCD0jaHh8JcmARu139ntCnZjQ3Lxbp4FMTW0SI7Kf9sY+p+C2dKEXezOahAM0w2CHdlMAXUYS8/6PfWhQxX2YggysDAV/GBCEhnuO4zJLHgjdEecErvQ
  template:
    metadata:
      name: stalwart-redis
      namespace: stalwart
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stalwart-bootstrap-admin
  namespace: stalwart
spec:
  encryptedData:
    credential: AgCTMSQtwJCDDPHWODf4+xPxWWBiDGcpPPc0i3cNU0xXR0PPR2gMgVBm5/UEZaDiD5U7DacWcMKavR59Cw/DN1lQEsVrvnuVkcsT5Cy7P92LQ+Kvt4L78CWddUoqjs+530Od225Fwh5A8eOKp1JY8hBNUR8PM16FZE+7UWjNiyehfULaSpJCGhRRMTwlLdtIXQvOZ93m9jy/SjfltqjJxfIVMm4X9SkniJQAAR84P4nIoJxMIer3aad8m20hFAQy6FT+0AV5PdvZYxTEnpDJX7+oMK9te624iKXvUSIybYeo2EYWjTUaYkfeD3pq4BG22OKvhSEeuNcEqSKksqS20SR29RZ6s9oL+tagJYSOoNl62y28IfCGQTo6cAczvdR5JdwBCHzI2jWHvBpeLgu9rpOfutO9EifP+QfyYO9wCXRh/iRMGh0meDKJkb+hQFAPk/pyrRQUOi9bELuvceGUUgPVbP7vwv6trBKfhUaslJMv90lZ4nOJcinZxmjuZF3s+KZBDgVDgY94psmFAuLZI9NFMpH/lAeOPmpLaIsxnR+jHT4SSTg0k7N9doREzTL6W6ZqqXwFwyAjl2fh44D3PCK1AYQAhUoBM6IybPcV6nkl+qnyRy53ZVv4WMuMb+AiBk+8LKLrWP3ujs7N+wVFcYafvri7CtQFJEk5CS4IV5lyeAEflK+E3qKGa0jDE7BYJ3xinqgRAOF6U3YdPYNC6FK0aqUmkJaCojZA4s0Jfi0y03ahhoSS0A7eroOmbU9qp8lUEvdUNISVEmcm1N0LriHXAvc4tJEF
    password: AgAwmHUwmU6kT7GuOWu856Om7Hq0R4qXUv+paODIKM2n/ccJY+VGoVn+3pYtgSiFgUusdwCmp/VGhqJHSZNC/8ihL/Jb3uIaFdnH/7dR/2IiNDYjaJx6FI0UV9Ff+NHmpw7MeekQdCJRe+Gr2d6q1yv9In42p3fG693DrlJXeYyUnH2I+0fbhunLUa9krsG97sQi5CmHHJ0jt/I9JU2ko7Emi9dQrSz7y6AERrWkF1yQhEryoKfWX4+R+5h8kcrdmglgH6z66ug01vfQvNVhKKpJE94nfBiBaMKrOOCQQJYnh/3pX/sxkRAHc/BhewH+UZDMw8tRjBPbb1eJl8wLsena/u2hxA4yYEWIJxTgxZXarmpLLkdY19EIou52m/DQ6NIv+ZvlO1fu4ZVK62s+dmSjuLk1WhjyQnDJ34Ry5a050a5YBCfG5kJoBu47YTYbYoYe0oPuTYCP/0UE1UdNG2POXmzK9A0V5ZJ920S9qk63+Kl3VJgl70Wtg8eJ5fhJmGnOXmTdgCfGhcb48L9rfvi8O2gdeChwP4/yq98ANWfmbBgATcS15RroDFrnDKWK325kQyLOOjVqxUALXaeWnUh2kt078LQKO6bhrP8z3MFexHXAeCMGH8gLpnLVH+Uc1nQGbHUgzOza/j7FktsIhIyWyivFiME2MDJA+y4BJXq3zAkTRbzACwHjdAbjUsZf/DrugnoG6GQIL86oH65MYy6/ubCDXcQUinOmnGi3GNbtLAWkma+uWkefq8rRGIkOp0soY4rlEEh/bpbdeA/niAer
  template:
    metadata:
      name: stalwart-bootstrap-admin
      namespace: stalwart
