---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stalwart-storage
  namespace: stalwart
spec:
  encryptedData:
    s3-secret-key: AgBUBii+pul4TJzBO1SVNqbP6Qz+O9QmoaB+yxOaCHRB9Nkt6KV9+pJXXuZJ0h0jOmrngpfVbDUJHrhKghHnlicWBMzcjY27O1seb7Q1I2kuweUcwaDsFQVw41dEbyRYQ23sakotkbVu4B6WYD0m1cbxSIpjYOnsmHMryAKvE2MmBSUTQlq4gUioyHU1nEuaUHcWPkPBtzh4leWv3ZKgkSjouv1qAmYJQj97wCMYEdN5J2xGZ81xlHeR4qB0QQZRXwzvSyHBgT+9ZT0edpCbi0dy4yFAa/8c9dROsGdSFRH0yux4I85PADgtpy/NViTWMK2wu0ouTXmP79V69eRLt/4t4i19X8LD3tueSZ+BEkCK6y776DNYWZHcePGt6HEvGha1/bmADHkFHABBjgSdNrKRSPWAK+jdo3w+TCQ0HcXXSGsL7thWK/Nqs7N7WIh44g+KQC7L8YdegRFM+5lRG5XxthxfBN9cVBJGSXh2yNqeqjAnbCbEHUbzOQ+4dWfAZnf9lHwefVutMkhWeEnjpVM6/SKONVLlpR0JF8RQeW/WWyaN4oXM/fJNhNQWizMxpKIzGNGtRMwD2QTMSlAy5jHjSC2GXL+h47cJ04faW5yrK4uza56Ek/TyHY2rLLmVuzyg6y60WTY/cw+kJLEffTL8kVAV0lAFveoHpn65q1TPGpfvelsB5oBLj+5TEpRDiB0AtK2hAs5VcYzU2/VyUDox1VlK90koA82afqplJSV9IEJ2Wp65vhIQBygoXfbmP7rJyO3a1yHV3TPXvzAbCVw3
  template:
    metadata:
      name: stalwart-storage
      namespace: stalwart
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stalwart-redis
  namespace: stalwart
spec:
  encryptedData:
    password: AgB+Ql8uCe0+lkXChZN9+kND63KwfpyzU23hQUj8TQtHdv1Uhc8kE6E6wY6Gb7USjwCccRT8GtEzx5SqDj1NoBly4hJLiMZJAK5k662UikyrIaewh4ceJzm1MAPFM03/phHapBvbsFfCtrXpmJv2YdD+fUjfH8HpEQ8CxWHhiREAg+tM+XGPLKB8mQvTOMNQzLR7JeBdeR3+M9EZyAH7UfA7mlXsgZUIskLMJ8BB/RkvuhoX9pTswTM0gMTenHCVoqll8N2uS+0pJn0ls7LHK6+ptr5ENHwDpvjimi+3HioNuCOATHSkFMzA9RcmbZFbdkUQJLcPXsma2/w8kLXoczgNENQoiWDT652BQy9EV1JYj65+c+oz2mt5r/izQbVb9VOAlRPyZlTwe9cEiyaZZbASrODvKNap8kRaZG+5cSgb5RUlMf9HfD4Mfp6HM/X/1mrBwJKpZAv6iQ8BuIfQdePT0nxcRvYuXoCSM1NnwU0qZuZAcZO0ZCRAX8IM7lfE8R3sx1nELe4zodXb3+kqlYaWP9UViSeUn27yFhUPE2rBODJJ5NDo0ZA8miZn2MzIYN08Ni0xfko66FUz91R12EuipcVBww01yRyjETZ5NlsEUtf6PFEcUa9Y+05boK8xFWYU2TcMEmbo1EnvGqFpkPcdYoTCa7bX61KuKCD0jaHh8JcmARu139ntCnZjQ3Lxbp4FMTW0SI7Kf9sY+p+C2dKEXezOahAM0w2CHdlMAXUYS8/6PfWhQxX2YggysDAV/GBCEhnuO4zJLHgjdEecErvQ
  template:
    metadata:
      name: stalwart-redis
      namespace: stalwart
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stalwart-bootstrap-admin
  namespace: stalwart
spec:
  encryptedData:
    credential: AgAr5Asz2vRJw2N+4mWKsl3dO1LMnBwojF7ITqZYNaUmbHE/eZVIT8cy7B0Dr2jevldZncT9RXjiRYaFqW8CXQ1q+sEMUz9R6O1FFzqtTrJdDqjitj8rvrhNdVVrsNgidRDQvQYIgWdTV5evF9/yPQaUkRgNMhx296mLofju0nk8CepRDQ7Qj79yscI9hY086IUtArIGPT5pA07w1ulk3+LJk3cTnlS3qJLAaSz3f6DsdUUkMJjik4b7e6vNYfRviELU8EJhAHcLMfd70L9DGob/+A/g5SJIRkqFelFdK6Q/h3/hOsZIqvzsLsOWiuGochptOvpru48UfatZdEntl6l/GNhrcJGq6/4dzVytiftqbzQL6xi7kpM9dlj2saL3sX99XHy8A/xi3K92zIvaBxOfKeqc+E3pzCtdZrV/WWEGTIB0CgB5+4J6oe797TnAps9K+AJauoERA9w8NBthxJMffT24an3hAkTA2wmLCzpT9pvGzwH/BgPFmkSuMY3Jq2i7uE8DC61TFj4iMP4SgTbACGhM/urzLUqCjOzxKI7FBkiNZ0uqPBXR6l+bUXsfvf7eZ80wX2LeHAgl9FsdZj9dyesgw12orHN2zRjrAS7o2GCfeZeuRPv2/ILnkbzWWd3kqAyRh85EYhy8Xq2/Y/5tMz2i5kU6V1YrZ2WraDAhLllfFpoZQ7dmY9U73IUgtpXSda4uyZeGfq8uVmrUathliqmKQHdO4PTGa+WTNqDXYbhg36qi0E4F2B4CEQvTg0Bv1m5ca2xRG9M0GVHvPHj1mRpbL8PEIl/BXNnAL3g=
    password: AgAwmHUwmU6kT7GuOWu856Om7Hq0R4qXUv+paODIKM2n/ccJY+VGoVn+3pYtgSiFgUusdwCmp/VGhqJHSZNC/8ihL/Jb3uIaFdnH/7dR/2IiNDYjaJx6FI0UV9Ff+NHmpw7MeekQdCJRe+Gr2d6q1yv9In42p3fG693DrlJXeYyUnH2I+0fbhunLUa9krsG97sQi5CmHHJ0jt/I9JU2ko7Emi9dQrSz7y6AERrWkF1yQhEryoKfWX4+R+5h8kcrdmglgH6z66ug01vfQvNVhKKpJE94nfBiBaMKrOOCQQJYnh/3pX/sxkRAHc/BhewH+UZDMw8tRjBPbb1eJl8wLsena/u2hxA4yYEWIJxTgxZXarmpLLkdY19EIou52m/DQ6NIv+ZvlO1fu4ZVK62s+dmSjuLk1WhjyQnDJ34Ry5a050a5YBCfG5kJoBu47YTYbYoYe0oPuTYCP/0UE1UdNG2POXmzK9A0V5ZJ920S9qk63+Kl3VJgl70Wtg8eJ5fhJmGnOXmTdgCfGhcb48L9rfvi8O2gdeChwP4/yq98ANWfmbBgATcS15RroDFrnDKWK325kQyLOOjVqxUALXaeWnUh2kt078LQKO6bhrP8z3MFexHXAeCMGH8gLpnLVH+Uc1nQGbHUgzOza/j7FktsIhIyWyivFiME2MDJA+y4BJXq3zAkTRbzACwHjdAbjUsZf/DrugnoG6GQIL86oH65MYy6/ubCDXcQUinOmnGi3GNbtLAWkma+uWkefq8rRGIkOp0soY4rlEEh/bpbdeA/niAer
  template:
    metadata:
      name: stalwart-bootstrap-admin
      namespace: stalwart
