apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: open-webui-db
  namespace: open-webui
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:${OPEN_WEBUI_POSTGRES_IMAGE_TAG}
  enableSuperuserAccess: false
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values: [${TALOS_WORKER_LEFT}, ${TALOS_WORKER_RIGHT}]
  postgresql:
    synchronous: {method: any, number: 1, dataDurability: preferred}
  storage:
    storageClass: openebs-local
    size: ${OPEN_WEBUI_DATABASE_STORAGE_SIZE}
  bootstrap:
    initdb:
      database: open_webui
      owner: open_webui
      secret: {name: open-webui-db-app}
  resources:
    requests: {cpu: 250m, memory: 512Mi}
    limits: {cpu: "2", memory: 2Gi}
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: open-webui-vector
  namespace: open-webui
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  name: open_webui
  owner: open_webui
  cluster: {name: open-webui-db}
  extensions:
    - {name: vector, ensure: present}
