---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-db-app
  namespace: open-webui
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    database-url: AgB3sxCwA47UBiId2SSJpKXPe+Zq/fYIqx04Bf5oB8aYonlDdX3dhDdnAgGjxJea9fXfpFK42NC8DOL0nJHgXW7Vh/Subc5Eoh37vuceZQA0V49EHxJHhixz/DtMalcpBeVDbrfSXpfo00FWj1aiwUPNefF1pETwNZSFDMoyD8uM6/7kLlEMZcqC4aJGX2r0wfgZxaVEkqq/7bYxDGv0Rfd6SsTrKKzdwwi/B0Xs2+a3568DnEh3qcCbmg+3WvBCmHsidHU8KMO1oxyo5YRM+SrPwC+z2qc2jP/QLwknq1X5cnnDoQ5UWJbP61C03A9wsjIQJ0td86pGnJDu7edEl7xYhk0bNvo/9Yr2Sr+TOS4ap45r6PCIneIKMROliyENxNqX0r/EHfUV/Oe7LY97DvnGUAn4XCvHn/qzaMswxLg7oH4FSrWJ7ijRr8pThOM8UMWRWmHpuG6/MrSNwiZ0x4tgyVdZf0Bnod4Sk0sqD+zXffi6dtE3dM1qUEApdMhrFWef6g5s3BvlkLKgwIN16Ia7gaCpNxgkfs9yAXQ8KfIABzJdagbFTqipXybE+phzyKMgfMvm5v3fKQKgya5Qr+X+mFiKxXnKelxy6IQEHP9TB4hxvYTGSa+zoUqZ4kKYVCHjENCV5Plu68w17QWcgZxCuTI5Y6CQSRl2yDjLTYFWOpmLXFKWIaoul7lGOgnBgG2pA0VMg8yVROgQ9UGBlhvr7c1B37CIwcQTeM6QpCW1F0UQh6QHi+uWm7vlvaMJKOJ62A8ItylWMbK6YQjuYQyBGNre1kI9w2ipWFBiXpBALg9tCVebveoG0ghs6zNziylt5ONwe3G0KatoFCurn5P68uB+cDoPff5VY2Jy8g3D7kcL+zF1/ra3j41c63yCjMsVWPlCRQg=
    password: AgA8tJOv1kBWQZGNkqcWRLM9Yb7V9jK9jPvPTavsQA5qemOZFfIExD380o22P5I2pJvRnt9uTfvuylO7CBOKwaLK96b/WqGoB3YM6sZhhMZl13ACq71Ou01tUDopsHIi4mS3F67AUXRgs5a3/32lrqsgIrnUay60SSSgx6Od3WwBlPPx//hV5KhXNwD8kKwhbP9UEaWsXbU1ivunnP816SdL7KX6h7GpJTlfL7WFuIwLYceWVPh8KFFXbWDuCopfASo3TCOIojWmZUFHAoQdl+bWqc32hqeoXOSeoK01ogN5hYG9Fc1VAMhGSYdACABxROzZq0uoueN+XOf6uonZhDvxbLLOiDdzYxIWxaDLWfjm/nyK3gC1qwfxHkqQImz52byxI3LoEfXxieVpSTAZAVuWwyjQaGyHXQQPu8ZGIGdThT94nR5wfycLBieQ8GRhzmVnumzpes8NXvWmoCQXfosmdqmMGWtru7Px5J5t9PVMDvyUn5cSdhDdv8OVnYk8dYknD4LMRbDrSK4y1Xzc8xeB3kMesb+s3+EOOBdp48ecnilcbsw5kOegp58oKxqcN2fMZ72SdmzxG6Rn54QBrJ29ANuAg8MfB4NJ4zC0GFc7tyNT9hsLrEFGCUo6VeRIHAhxd+MxD7gQxlLCWVzjnGS3iZERAlLZiZTYycPkmMl6GgeIWhOrNEsljkxmzO9Mxg9N5eJdH8mw4HzcYxlSlMs+dEX75IIJQ8/mePY6P/NKjO1YoBZTd2bllWfBRoqoXRs9AlUWG8tpX3XuZAlcIFGn
    username: AgCHs/bn4xSBu2aNFBPhUIyeKyshkU/HO9fmYyNJ20kKHfof2R8mbXCw5xV8VQ5BOQ6s5BPQwlWECxzWYm5bK964HBvAyo90YuF/gQCFT2/O4AkAygjcmTfO1U8I9ydI4I3J2krLiJypejDT7CYQUS8R+2yB4OJMwczoHC9cbR/TNALI4LUhS6fcNhvwxJUkSP6D4VmudDwPdrKSV6iEeBqlsssLTt0s+WMESdQgN9O6O3qPoccJrWXcH+P+ojiQKWXMtm1/uB305xtQ4fVH4sCDEeAwcNp4FBj4YheyN7KGXpa8t+tKg/BKZJGuimZYKAJ6nc2qI6q02ghEGdwvd9/z0oGbioktvAp/AKeI9a/rh3YBy86aIZZ4q0jm0pCCgQY1/IjH+/3srAgkFqKm4FU9SPVTqFhI36nT4hhSbnDBAAzvvo2xRoJnHzPIV8SwIb6Pbh76/g8cilcyqcGAybkl38h9wwAh8bQsaLuIk8sDHQchakIVMVehRhiy5m8adoON1o9tHxdvyy54TR+WDNC41lorKlJyp7Q79h5J15j0DIGXWY5ORL+mJxqQABFhxhTg8i89F0t0qnP13b5qDW84XQiM0eIW/mfL/PS8pJjFwI//i0aDLePLF69pOmO/xrAgwO4P37Ku6gmRg3k9Kd357AaVdfP3ayoexPUeqt6AMlMrgEQlusMmWUUXyKqH+loEIALkNZqCKO96
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
      name: open-webui-db-app
      namespace: open-webui
    type: kubernetes.io/basic-auth
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-redis
  namespace: open-webui
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgAjUx3zOLVF4HQ1fYlDzqMxqq10zO8JWYXkX23AigU8UnOj8GU8gS6CYziJRi1aiNdGysxwCZrI7xVoqDm4MDQPMvdiMR/d4UZAJ7PoyAenmchnSP/2UKbeJogrO2/ewPCaRniCeT22+j6E4ehlIQir0iXCPM8WHjXWarokC+7jZKgIu1a8nX7yl5RqeMLZkGybjS4bQfvMy+OPDt8iRcl3qfoO9dxY+2sTgxHYjbDDAqvHemABMZlJe6bNroDwlPbEzghULWNAwesfoqzIvDAzWFsDdB/CxDFYhAMqIyf5BM97tgBKeOypwHdLMH84MDrEUraCITGWXDSsN+gVnn8oLDOy2WKD9tTk/Jxd0TicTwENLN/5WerldC+hi1+lra015YLRMj7QfElC9opjN4O0++7yhiynVL+u/EU/BXY/HATtvB0Fq9tYNkmJqd+ahFXN2yxVtWmoFO2YBOFi9CcZlRKr6krAbcdFybgbIiWGFRwscDWd0UJQegNSKihONCLbH0Plz2jO+Zp/2uKCY2+IlaC7EuALaWJ/Vu7kSbuQZYDFKvYCKDLQPlW6x/5PDZ9J7iax7mDRnD2LHkllTDRJdohAtNZjqOXqloaaUxpxHmnF7uwjN7+aHIXwvTLkZWQXKsNkXxsn+qwbJI8R+Vn7VMCIML/pEZeWxVMpVlebkoaXFaBIwh1eheZ/9FljiIE6mq1kjOoE7fTaACjGrnBlSfn8oj5JU0LUrrI67Id9HhDLulDR0tGXbMr8t6K8go5tTXdPwizS0ZkRCXF0kHzv
    redis-url: AgCsor5q8XPG58qVI2ShKXZVVopiEwx+/HzySZPLghNBQOdGLrcgb6p0lXbCtt7SAM8w/Q1OGi5YEekWuOOrn4SHkCEBe+evwlg5fldf/ix0BhdVpYFyMMD5R+kkxFKN2Ugc3D/hbPSBPs/23fuZoV5fz/YkHci9Xacc1p6jvoP644sss4DcEjRAFhnKzwh4Z3azUJ9NTnCVeGlz/pwuT2eQT4/1PkEQZdwhWMy0YWMewkcK1rGAC+SHp0BE65ahYqpnKuf65q/xkeITxf9YsA4aogZ/JbKbYuNtKZlA1sSUQRVGM3liJpXKLsggUJknzt0/ysChYisVyUH7xg+FJ2KY22ph7Hth/S4/TX7eamJMBuncQrZLsju3Q9sSzQStHrtkWG4Oes3/nEWta5oN3gGZpYsNC7Yo7b+dk3cFe108QaIl/Ej5qbryUphRNuO4vd3gjKlgRlBxLLt2mD8Ic9GS7Dfe9xnJ9rl0B9GwBniZW8zyK1zowjr/FxNErzCSj/9qjNGWy3i867KjWQFE0fvdGmeLK5JZVIkdHg1CWymh9urAsEHYLq69vQeKwrF9s78uv4UAW6tZPIGInIst+fGgv8A3IoN3AqiqNVgp0GDSCpxSJEcTZMdekDcKaQDEr3rlrX/Oapfauixy+7QLm6/tEUe/JzqTMkp7Jg2yT9l/ZdyGeM+gGhS7S8+QD8H0V5i0vBVOID23gzx4EkrMiNzOPdnbvO80tPoWQqVSb+BN/9Zs1T1HY1FiukT72WircnJhMsIuR5Sj8SqO+ow5D9uWN8hyDgAsUMW2u+y2jm+z/kykMmXb6zxxMv5m
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
      name: open-webui-redis
      namespace: open-webui
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-app
  namespace: open-webui
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    s3-secret-key: AgAiARUUC2kohhCMTIPT+4CUSrpqZxdVmqULyHKnR+m3CnY6Cb4C4HfO7c+xBcI06H/+7sbcchqesqdUBv4C230oksFsOkiofhilAy/wBhy/ek5daUvlvv1NOzWTl9EKBu6LDDOyuXxf/srKigNeQ2yOJiyHDYOpmKebldFdAl+KofmADEuO10lAzQhsTCihc8CXXej6ditUgs4zusV2uBtwf3rczLpd3d0PNXLVjBly0jqppvnyNsBYCXdCcJ/OGyz7wOAs5HGrdJWJ9vwKqnqmI0NHdce/sUHvjWD8RiCgJW1317z18nbBolMGmuMwzNp/GrKmROQQVK/mcnuCqz5/sDqG/Kk5oarWTp88JppUqnTp2ipMk9nMAl6yAVqQBwYbSm31RkWXgUkkiERLurfIRpBWLxBAEfZss+C0xCmY+OBphQCBTVddCEDQXDK3l8ENojmyG3vOyvjjJpH5LDmREwYf4jjVPlEA3mtkwa3j/02JlYCTXiFBGLoUDGKfp60lUAN8c/U4oSr0h9pv2Mx6iKGCdpA5tCREXLXeqOeZvM65U+4xrZ2Ea8KKkahYWM5E6/ciotDYxaooBxMIUpl3Jms/ozhXeG2EqJS1Gf2t5PL5r8CQ3OmuXBSX2DN8QSWpX4KRfljqUBn8fQWxu+1I3W21aF4wJnVO77lK3AJ97xJqkjOF89csFpArZNYp83E1vZgHfjkPrlhpSlDNoMyWdBN3Z+9XfSMTtUIFv8ny8MlZnRx4BYNZZYLmkRtMPtAOijVxBcvL8kpu14aeWiZL
    webui-secret-key: AgAVy3gkJdGgwBa6oBiwg1jIDYai1pVVm92czlVxEhr+Z2Zttjcd+E58mQfRHs5hKC4okL+P5nLwUAe6Zkks8CEIl1m/rbjqC/+JkUn82W9MfkUOZnOKAnqrB3EudtevXuTgwtVuE5lXNcdFMgb8WJFnxwyHu70LdEbQoP3PZMa3sluIJCuuuwP+nRsBZ4BnIF20Fce4hjgRB24Aextj6hSOYJ/9teEpLhg4++k4NEcMvnb3pIztchYNmyw5R+oEAOm0EFsV6Md6SDk4l4vShETW2d7reV3xtlPtRN1SH5a2FBl457qDt/7PrglqzGMuPWAC/34oXjPowYYVjmYpIYbTxTHxs7P+G1DcOOSqgsKPzTMEYRzqvU6BCotUcxAtCRUriX2oi/80rylq+s7gEhqzNo/QRvRidsg3/z2J5YMp5RDPW1GVqxk1Q2ufJ+QgVeP6s3vSCr84YKHLZ+a62eV4WC8xYSgwF6uJRWhlIvf4qUSdMukIyUQosOtZDjTmhArbCphYBTBEAuv+Hf7D6ZDoCckqWs1ZRrHgj3B1CJ7JbriAXQIdPBS4hTfRvCX2UMwPIlDy6WEs4V2Kk3gyRKzo+irk1nCgYFvQv9izhK3E5aodNkHSxgQAVmNKC2WIlVqXWUqOln91es4QthPEYlaDI/s1WOujil5ISAeJ93FwWlMEUnOittge2Bi45tfoRA8ycotD5NE1auJRMANwUC942fd4rTddNs34FvkTbqc/xY5vyUssZ4jWkQq+83hB8zl0zxIHK5SJmIS8uZkoJWGV
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
      name: open-webui-app
      namespace: open-webui
