apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    dex.authentik.clientSecret: AgCiu8S9pp/Zwsuiu2lzFK/reQ4YdpDZ9NK050xje6wVLWb0hm92WRv3RfGVME2uRfScJgURlQpIdyRf7BrLmGCFOFxZ/dCw1pcJXiqlhrb5hzRaDmXj2NlYYDS6MQp9TH7TcHinoXAvzV1Yl6mqcGV+b41vGaJVvYwOEVyCUwKjSChulIQ+hMcy7ydGxE7BYa34VKRIOFdNeEjuEudFheacdybA6igiokEebXC6X6kFmsV92Rn48fmivBaOG5y3uuo88XNy/GKNySQHqdcu1h3h6BFST5oDPzTm2V1tasyWL7Czh5WISKYWRtPnqF0iOXOGaezlpHf7StVEkvRISfC+wTFsGiGCXCp7OdadimjxwB3+HlEcud/GWjhUjysZbY2NtUPgeW8Fr7tQ631MiKWwFg6HY+c2La92/AAOGsUsYJFCfytqfnHKJmtTZ1ZumtZCKJWoIivPUiGoQFTSBqDjoqcdKg4t8j7CnS4oaDoPidXzKolZk3FFdhDRf8aFcXJkZBDXbUvwIcMUgKuleNbdriFJfHQzGPLSPqKvNv4q/c4guoLZOhkna31HhftX6BswBgq3zBT3jPFaouJ2N76ZaaoQ1x1hfzjmZwoUX34v7hjwu0PtJKzNNKJshXRTFVLzr0F1CISsxNeFeP5M4Hp0p+1i6GTYluR4Si67woZ0FsgeYgRkPuf23FB7fcLiMvpiNl1EATC1/BsZx722dUTEuAe6UFc5RmgRkP99ZhlC+iDHh1sqaQK/OSsUrDprgavCWpW3axsMw4UYjqN7T9z3bUqWKx5vuSnUEJjH5xu3RBEs0k9PN/v84TGM7CBPGISrk4R+ObE5SDPvhuxPng/u9kgOEhOInPg/5fP0nOj7yA==
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
      annotations:
        sealedsecrets.bitnami.com/patch: "true"
    type: Opaque
